//
//  clipboard+Options.swift
//  SiriusKit
//
//  Auto-generated by mdproto-gen-swift. DO NOT EDIT.
//

import Foundation

public struct ClipboardDataFlags: OptionSet, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// 클립보드 데이터가 생략되었음을 나타냅니다.
    /// (예: 대용량 데이터, 보안상 이유 등)
    public static let omitted = ClipboardDataFlags(rawValue: 0x1)
}
