//
//  fsaccess_mount+Options.swift
//  SiriusKit
//
//  Auto-generated by mdproto-gen-swift. DO NOT EDIT.
//

import Foundation

public struct OpenFlags: OptionSet, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// Subsequent writes always append to the end of the file, ignoring `WriteRequest.offset`. (POSIX: O_APPEND)
    public static let append = OpenFlags(rawValue: 0x1)
    /// If the final path component is a symbolic link, the open MUST fail with `loop`. (POSIX: O_NOFOLLOW)
    public static let noFollowSymlinks = OpenFlags(rawValue: 0x2)
    /// The handle is opened for directory access only and may be used with `ReadDir`. Fails with `notDirectory` if the path is not a directory.
    public static let directoryOnly = OpenFlags(rawValue: 0x4)
}

public struct FileAttributes: OptionSet, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// File is hidden. (POSIX: dotfile convention; Windows: FILE_ATTRIBUTE_HIDDEN)
    public static let hidden = FileAttributes(rawValue: 0x1)
    /// File is read-only. (POSIX: synthesized from permission bits; Windows: FILE_ATTRIBUTE_READONLY)
    public static let readOnly = FileAttributes(rawValue: 0x2)
    /// File is a system file. (POSIX: synthesized; Windows: FILE_ATTRIBUTE_SYSTEM)
    public static let system = FileAttributes(rawValue: 0x4)
    /// File is marked for archiving. (POSIX: synthesized; Windows: FILE_ATTRIBUTE_ARCHIVE)
    public static let archive = FileAttributes(rawValue: 0x8)
}
