//
//  fsaccess+Constants.swift
//  SiriusKit
//
//  Auto-generated by mdproto-gen-swift. DO NOT EDIT.
//

import Foundation

public struct AccessMode: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// Read-only access. Write operations on a handle obtained with this mode MUST fail with `permissionDenied`.
    public static let read = AccessMode(rawValue: 0)
    /// Write-only access. Read operations on a handle obtained with this mode MUST fail with `permissionDenied`.
    public static let write = AccessMode(rawValue: 1)
    /// Read-write access.
    public static let readWrite = AccessMode(rawValue: 2)
}

public struct FileSystemErrorCode: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// Reserved for unset or unknown error codes (e.g., field not populated).
    public static let unspecified = FileSystemErrorCode(rawValue: 0)

    // General

    /// Internal implementation error (uncaught exception, etc.).
    public static let `internal` = FileSystemErrorCode(rawValue: 1)
    /// One or more arguments are invalid (negative length, malformed structure, etc.).
    public static let invalidArgument = FileSystemErrorCode(rawValue: 2)
    /// The operation is not supported by this entry or filesystem.
    public static let notSupported = FileSystemErrorCode(rawValue: 3)

    // Handle / Session

    /// The handle does not exist or has expired. (POSIX: EBADF)
    public static let invalidHandle = FileSystemErrorCode(rawValue: 10)
    /// The session does not exist (e.g., the `sessionId` was never issued, or its mount channel is no longer active).
    public static let invalidSession = FileSystemErrorCode(rawValue: 11)
    /// The mount session was released while the operation was in flight.
    public static let notMounted = FileSystemErrorCode(rawValue: 12)

    // Path / Entry

    /// File or directory was not found. (POSIX: ENOENT)
    public static let notFound = FileSystemErrorCode(rawValue: 20)
    /// File or directory already exists. (POSIX: EEXIST)
    public static let alreadyExists = FileSystemErrorCode(rawValue: 21)
    /// Target is not a directory. (POSIX: ENOTDIR)
    public static let notDirectory = FileSystemErrorCode(rawValue: 22)
    /// Target is a directory. (POSIX: EISDIR)
    public static let isDirectory = FileSystemErrorCode(rawValue: 23)
    /// Directory is not empty. (POSIX: ENOTEMPTY)
    public static let notEmpty = FileSystemErrorCode(rawValue: 24)
    /// Path string is too long. (POSIX: ENAMETOOLONG)
    public static let pathTooLong = FileSystemErrorCode(rawValue: 25)
    /// Symbolic link loop detected. (POSIX: ELOOP)
    public static let loop = FileSystemErrorCode(rawValue: 26)
    /// Path normalization failed (e.g., contains `..` traversal, NUL bytes, or invalid UTF-8).
    public static let invalidPath = FileSystemErrorCode(rawValue: 27)
    /// Cross-device rename was attempted. (POSIX: EXDEV)
    public static let crossDevice = FileSystemErrorCode(rawValue: 28)

    // Permission / Policy

    /// Filesystem-level permission denied. (POSIX: EACCES)
    public static let accessDenied = FileSystemErrorCode(rawValue: 40)
    /// The operation itself is not permitted. (POSIX: EPERM)
    public static let permissionDenied = FileSystemErrorCode(rawValue: 41)
    /// The filesystem or mount is read-only. (POSIX: EROFS)
    public static let readOnlyFilesystem = FileSystemErrorCode(rawValue: 42)
    /// The exposing peer's policy denied the operation.
    public static let policyViolation = FileSystemErrorCode(rawValue: 43)
    /// The user denied the mount consent dialog.
    public static let consentDenied = FileSystemErrorCode(rawValue: 44)

    // Resource

    /// No space left on device. (POSIX: ENOSPC)
    public static let diskFull = FileSystemErrorCode(rawValue: 60)
    /// File would exceed the maximum allowed size. (POSIX: EFBIG)
    public static let fileTooLarge = FileSystemErrorCode(rawValue: 61)
    /// Quota exceeded (POSIX: EDQUOT, or Pattern A hard threshold violation).
    public static let quotaExceeded = FileSystemErrorCode(rawValue: 62)
    /// Too many open handles for this mount channel. (POSIX: EMFILE)
    public static let tooManyHandles = FileSystemErrorCode(rawValue: 63)

    // State

    /// Resource is busy and the operation cannot proceed. (POSIX: EBUSY)
    public static let busy = FileSystemErrorCode(rawValue: 80)
    /// Handle refers to an entry that no longer exists or has been replaced. (POSIX: ESTALE)
    public static let staleHandle = FileSystemErrorCode(rawValue: 81)

    // I/O

    /// Low-level I/O error. (POSIX: EIO)
    public static let ioError = FileSystemErrorCode(rawValue: 90)

    // Channel Lifecycle

    /// The channel is in the process of closing and rejects new operations.
    public static let channelClosing = FileSystemErrorCode(rawValue: 100)
}
