//
//  fsaccess_mount+Constants.swift
//  SiriusKit
//
//  Auto-generated by mdproto-gen-swift. DO NOT EDIT.
//

import Foundation

public struct CreateDisposition: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// Open the existing file. Fails with `notFound` if the file does not exist.
    public static let openExisting = CreateDisposition(rawValue: 0)
    /// Create a new file. Fails with `alreadyExists` if the file already exists. (POSIX: O_CREAT | O_EXCL)
    public static let createNew = CreateDisposition(rawValue: 1)
    /// Create a new file, or truncate to zero length if it already exists. (POSIX: O_CREAT | O_TRUNC)
    public static let createAlways = CreateDisposition(rawValue: 2)
    /// Open the existing file, or create it if it does not exist. (POSIX: O_CREAT)
    public static let openOrCreate = CreateDisposition(rawValue: 3)
    /// Open and truncate the existing file. Fails with `notFound` if the file does not exist. (POSIX: O_TRUNC)
    public static let truncateExisting = CreateDisposition(rawValue: 4)
}

public struct FileType: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// Type could not be determined or is intentionally unspecified.
    public static let unknown = FileType(rawValue: 0)
    /// Regular file.
    public static let file = FileType(rawValue: 1)
    /// Directory.
    public static let directory = FileType(rawValue: 2)
    /// Symbolic link.
    public static let symlink = FileType(rawValue: 3)
    /// Other type (block device, character device, FIFO, socket, etc.).
    public static let other = FileType(rawValue: 99)
}
