//
//  fsaccess+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius-swift. DO NOT EDIT.
//

import Foundation
internal import SwiftProtobuf

public extension MessageOpcode {
    static let fileSystemListRequest: MessageOpcode = MessageOpcode(rawValue: 0x8001)
    static let fileSystemListResponse: MessageOpcode = MessageOpcode(rawValue: 0x8002)
    static let fileSystemMountRequest: MessageOpcode = MessageOpcode(rawValue: 0x8003)
    static let fileSystemMountResponse: MessageOpcode = MessageOpcode(rawValue: 0x8004)
    static let fileSystemUnmountRequest: MessageOpcode = MessageOpcode(rawValue: 0x8005)
    static let fileSystemUnmountResponse: MessageOpcode = MessageOpcode(rawValue: 0x8006)
}

public struct FileSystemEntry: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemEntry

    public let id: UUID
    public let name: String
    public let metadata: [String: String]
    public let flags: UInt32

    public init(id: UUID, name: String, metadata: [String: String], flags: UInt32) {
        self.id = id
        self.name = name
        self.metadata = metadata
        self.flags = flags
    }

    init(from protobuf: ProtobufMessage) throws {
        self.id = UUID(msgdef: protobuf.id)
        self.name = protobuf.name
        self.metadata = protobuf.metadata
        self.flags = protobuf.flags
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.id = id.asMsgDef()
        message.name = name
        message.metadata = metadata
        message.flags = flags

        return message
    }
}

public struct ErrorInfo: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo

    public let code: FileSystemErrorCode
    public let message: String
    public let platformCode: Int32?
    public let platformName: String?

    public init(code: FileSystemErrorCode, message: String, platformCode: Int32?, platformName: String?) {
        self.code = code
        self.message = message
        self.platformCode = platformCode
        self.platformName = platformName
    }

    init(from protobuf: ProtobufMessage) throws {
        self.code = FileSystemErrorCode(rawValue: protobuf.code)
        self.message = protobuf.message
        self.platformCode = protobuf.hasPlatformCode ? protobuf.platformCode : nil
        self.platformName = protobuf.hasPlatformName ? protobuf.platformName : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var pb = ProtobufMessage()

        pb.code = code.rawValue
        pb.message = message
        if let val = self.platformCode {
            pb.platformCode = val
        }
        if let val = self.platformName {
            pb.platformName = val
        }

        return pb
    }
}

public struct FileSystemListRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListRequest

    public let requestId: UInt64
    public let flags: UInt32

    public init(requestId: UInt64, flags: UInt32) {
        self.requestId = requestId
        self.flags = flags
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.flags = protobuf.flags
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.flags = flags

        return message
    }
}

public struct FileSystemListResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListResponse

    public let requestId: UInt64
    public let success: Bool
    public let entries: [FileSystemEntry]
    public let error: ErrorInfo?

    public init(requestId: UInt64, success: Bool, entries: [FileSystemEntry], error: ErrorInfo?) {
        self.requestId = requestId
        self.success = success
        self.entries = entries
        self.error = error
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.success = protobuf.success
        self.entries = try protobuf.entries.map { try FileSystemEntry(from: $0) }
        self.error = protobuf.hasError ? try ErrorInfo(from: protobuf.error) : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.success = success
        message.entries = entries.map { $0.toProtobufMessage() }
        if let val = self.error {
            message.error = val.toProtobufMessage()
        }

        return message
    }
}

public struct FileSystemMountRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountRequest

    public let requestId: UInt64
    public let entryId: UUID
    public let requestedAccess: AccessMode
    public let reason: String?
    public let flags: UInt32

    public init(
        requestId: UInt64,
        entryId: UUID,
        requestedAccess: AccessMode,
        reason: String?,
        flags: UInt32
    ) {
        self.requestId = requestId
        self.entryId = entryId
        self.requestedAccess = requestedAccess
        self.reason = reason
        self.flags = flags
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.entryId = UUID(msgdef: protobuf.entryID)
        self.requestedAccess = AccessMode(rawValue: protobuf.requestedAccess)
        self.reason = protobuf.hasReason ? protobuf.reason : nil
        self.flags = protobuf.flags
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.entryID = entryId.asMsgDef()
        message.requestedAccess = requestedAccess.rawValue
        if let val = self.reason {
            message.reason = val
        }
        message.flags = flags

        return message
    }
}

public struct FileSystemMountResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountResponse

    public let requestId: UInt64
    public let success: Bool
    public let sessionId: UUID
    public let grantedAccess: AccessMode
    public let error: ErrorInfo?
    public let supportsLocks: Bool

    public init(
        requestId: UInt64,
        success: Bool,
        sessionId: UUID,
        grantedAccess: AccessMode,
        error: ErrorInfo?,
        supportsLocks: Bool
    ) {
        self.requestId = requestId
        self.success = success
        self.sessionId = sessionId
        self.grantedAccess = grantedAccess
        self.error = error
        self.supportsLocks = supportsLocks
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.success = protobuf.success
        self.sessionId = UUID(msgdef: protobuf.sessionID)
        self.grantedAccess = AccessMode(rawValue: protobuf.grantedAccess)
        self.error = protobuf.hasError ? try ErrorInfo(from: protobuf.error) : nil
        self.supportsLocks = protobuf.supportsLocks
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.success = success
        message.sessionID = sessionId.asMsgDef()
        message.grantedAccess = grantedAccess.rawValue
        if let val = self.error {
            message.error = val.toProtobufMessage()
        }
        message.supportsLocks = supportsLocks

        return message
    }
}

public struct FileSystemUnmountRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountRequest

    public let requestId: UInt64
    public let sessionId: UUID
    public let flags: UInt32

    public init(requestId: UInt64, sessionId: UUID, flags: UInt32) {
        self.requestId = requestId
        self.sessionId = sessionId
        self.flags = flags
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.sessionId = UUID(msgdef: protobuf.sessionID)
        self.flags = protobuf.flags
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.sessionID = sessionId.asMsgDef()
        message.flags = flags

        return message
    }
}

public struct FileSystemUnmountResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountResponse

    public let requestId: UInt64
    public let success: Bool
    public let error: ErrorInfo?

    public init(requestId: UInt64, success: Bool, error: ErrorInfo?) {
        self.requestId = requestId
        self.success = success
        self.error = error
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.success = protobuf.success
        self.error = protobuf.hasError ? try ErrorInfo(from: protobuf.error) : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.success = success
        if let val = self.error {
            message.error = val.toProtobufMessage()
        }

        return message
    }
}
