//
//  simplerpc+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius-swift. DO NOT EDIT.
//

import Foundation
internal import SwiftProtobuf

public extension MessageOpcode {
    static let simpleRpcRequest: MessageOpcode = MessageOpcode(rawValue: 0x8001)
    static let simpleRpcResponse: MessageOpcode = MessageOpcode(rawValue: 0x8002)
}

public struct SimpleRPCRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Simplerpc_SimpleRPCRequest

    public let requestId: UUID
    public let operation: String
    public let args: [String]

    public init(requestId: UUID, operation: String, args: [String]) {
        self.requestId = requestId
        self.operation = operation
        self.args = args
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = UUID(msgdef: protobuf.requestID)
        self.operation = protobuf.operation
        self.args = protobuf.args
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestId.asMsgDef()
        message.operation = operation
        message.args = args

        return message
    }
}

public struct SimpleRPCResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Simplerpc_SimpleRPCResponse

    public let requestId: UUID
    public let code: SimpleRPCErrorCode
    public let retval: String?

    public init(requestId: UUID, code: SimpleRPCErrorCode, retval: String?) {
        self.requestId = requestId
        self.code = code
        self.retval = retval
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = UUID(msgdef: protobuf.requestID)
        self.code = SimpleRPCErrorCode(rawValue: protobuf.code)
        self.retval = protobuf.hasRetval ? protobuf.retval : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestId.asMsgDef()
        message.code = code.rawValue
        if let val = self.retval {
            message.retval = val
        }

        return message
    }
}
