//
//  msgdef/v1/channels/transfer+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius-swift. DO NOT EDIT.
//

import Foundation
internal import SwiftProtobuf

public extension MessageOpcode {
    static let transferStartNotification: MessageOpcode = MessageOpcode(rawValue: 0x8001)
    static let transferDataChunk: MessageOpcode = MessageOpcode(rawValue: 0x8002)
    static let transferReady: MessageOpcode = MessageOpcode(rawValue: 0x8003)
}

public struct TransferStartNotification: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Transfer_TransferStartNotification

    public let name: String
    public let totalSize: UInt64
    public let contentType: String
    public let description: String

    public init(name: String, totalSize: UInt64, contentType: String, description: String) {
        self.name = name
        self.totalSize = totalSize
        self.contentType = contentType
        self.description = description
    }

    init(from protobuf: ProtobufMessage) throws {
        self.name = protobuf.name
        self.totalSize = protobuf.totalSize
        self.contentType = protobuf.contentType
        self.description = protobuf.description_p
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.name = name
        message.totalSize = totalSize
        message.contentType = contentType
        message.description_p = description

        return message
    }
}

public struct TransferReady: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Transfer_TransferReady

    public let compressionMethod: CompressionMethod

    public init(compressionMethod: CompressionMethod) {
        self.compressionMethod = compressionMethod
    }

    init(from protobuf: ProtobufMessage) throws {
        self.compressionMethod = CompressionMethod(rawValue: protobuf.compressionMethod)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.compressionMethod = compressionMethod.rawValue

        return message
    }
}

public struct TransferDataChunk: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Transfer_TransferDataChunk

    public let sequenceNumber: UInt64
    public let data: Data
    public let crc32: UInt32?
    public let isEof: Bool

    public init(sequenceNumber: UInt64, data: Data, crc32: UInt32?, isEof: Bool) {
        self.sequenceNumber = sequenceNumber
        self.data = data
        self.crc32 = crc32
        self.isEof = isEof
    }

    init(from protobuf: ProtobufMessage) throws {
        self.sequenceNumber = protobuf.sequenceNumber
        self.data = protobuf.data
        self.crc32 = protobuf.hasCrc32 ? protobuf.crc32 : nil
        self.isEof = protobuf.isEof
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.sequenceNumber = sequenceNumber
        message.data = data
        if let crc32 = crc32 {
            message.crc32 = crc32
        }
        message.isEof = isEof

        return message
    }
}
