// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/projection/accessibility.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
internal import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// Represents the value of an accessibility node.
struct Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue.OneOf_Value? = nil

  var textValue: String {
    get {
      if case .textValue(let v)? = value {return v}
      return String()
    }
    set {value = .textValue(newValue)}
  }

  var boolValue: Bool {
    get {
      if case .boolValue(let v)? = value {return v}
      return false
    }
    set {value = .boolValue(newValue)}
  }

  var intValue: Int64 {
    get {
      if case .intValue(let v)? = value {return v}
      return 0
    }
    set {value = .intValue(newValue)}
  }

  var floatValue: Float {
    get {
      if case .floatValue(let v)? = value {return v}
      return 0
    }
    set {value = .floatValue(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Value: Equatable, Sendable {
    case textValue(String)
    case boolValue(Bool)
    case intValue(Int64)
    case floatValue(Float)

  }

  init() {}
}

//// An image snapshot of a node.
struct Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// MIME type of the image (e.g., "image/png")
  var mimeType: String = String()

  //// Image data (binary)
  var data: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// Represents a node in the accessibility tree.
//// Each node has a unique ID and forms a tree through parent-child relationships.
struct Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Unique ID of the node
  var id: Sirius_Msgdef_SRUUID {
    get {return _storage._id ?? Sirius_Msgdef_SRUUID()}
    set {_uniqueStorage()._id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {return _storage._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {_uniqueStorage()._id = nil}

  //// ID of the parent node. Omitted for the root node.
  var parentID: Sirius_Msgdef_SRUUID {
    get {return _storage._parentID ?? Sirius_Msgdef_SRUUID()}
    set {_uniqueStorage()._parentID = newValue}
  }
  /// Returns true if `parentID` has been explicitly set.
  var hasParentID: Bool {return _storage._parentID != nil}
  /// Clears the value of `parentID`. Subsequent reads from it will return its default value.
  mutating func clearParentID() {_uniqueStorage()._parentID = nil}

  //// Role of the node
  /// @constset: AccessibilityNodeRole
  var role: String {
    get {return _storage._role}
    set {_uniqueStorage()._role = newValue}
  }

  //// State hints for the node
  /// @optionset: AccessibilityNodeHint
  var hint: UInt32 {
    get {return _storage._hint}
    set {_uniqueStorage()._hint = newValue}
  }

  //// Position and size of the node on screen (relative to the top-left corner of the window, in pixels)
  var bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect {
    get {return _storage._bounds ?? Sirius_Msgdef_V1_Channels_Projection_SRRect()}
    set {_uniqueStorage()._bounds = newValue}
  }
  /// Returns true if `bounds` has been explicitly set.
  var hasBounds: Bool {return _storage._bounds != nil}
  /// Clears the value of `bounds`. Subsequent reads from it will return its default value.
  mutating func clearBounds() {_uniqueStorage()._bounds = nil}

  //// Position and size in the node's local coordinate system
  var localBounds: Sirius_Msgdef_V1_Channels_Projection_SRRect {
    get {return _storage._localBounds ?? Sirius_Msgdef_V1_Channels_Projection_SRRect()}
    set {_uniqueStorage()._localBounds = newValue}
  }
  /// Returns true if `localBounds` has been explicitly set.
  var hasLocalBounds: Bool {return _storage._localBounds != nil}
  /// Clears the value of `localBounds`. Subsequent reads from it will return its default value.
  mutating func clearLocalBounds() {_uniqueStorage()._localBounds = nil}

  //// Human-readable description of the node
  var description_p: String {
    get {return _storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  //// Value of the node. For text elements this is textValue, for toggles this is boolValue, etc.
  var value: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue {
    get {return _storage._value ?? Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue()}
    set {_uniqueStorage()._value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  var hasValue: Bool {return _storage._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  mutating func clearValue() {_uniqueStorage()._value = nil}

  //// Image snapshot of the node. Only provided when the includeSnapshots flag is set.
  var snapshot: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot {
    get {return _storage._snapshot ?? Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot()}
    set {_uniqueStorage()._snapshot = newValue}
  }
  /// Returns true if `snapshot` has been explicitly set.
  var hasSnapshot: Bool {return _storage._snapshot != nil}
  /// Clears the value of `snapshot`. Subsequent reads from it will return its default value.
  mutating func clearSnapshot() {_uniqueStorage()._snapshot = nil}

  //// HTML DOM attributes or GUI system-specific attributes.
  //// e.g., "dom.aria-label": "閉じる", "dom.disabled": "true"
  var attributes: Dictionary<String,String> {
    get {return _storage._attributes}
    set {_uniqueStorage()._attributes = newValue}
  }

  //// Additional metadata for the client.
  //// Implementation-specific keys SHOULD use reverse domain name format.
  //// e.g., "app.noctiluca.x-display-id": "1", "app.noctiluca.x-bundle-id": "com.leaves.shizuku"
  var metadata: Dictionary<String,String> {
    get {return _storage._metadata}
    set {_uniqueStorage()._metadata = newValue}
  }

  //// List of child nodes. MAY be omitted depending on the request.
  var children: [Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode] {
    get {return _storage._children}
    set {_uniqueStorage()._children = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

//// Requests the accessibility tree.
/// @opcode: 0x8101
struct Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// ID of the node from which to retrieve the accessibility tree.
  //// The subtree rooted at this node will be returned.
  //// If omitted, the entire accessibility tree of the current GUI session is returned.
  var nodeID: Sirius_Msgdef_SRUUID {
    get {return _nodeID ?? Sirius_Msgdef_SRUUID()}
    set {_nodeID = newValue}
  }
  /// Returns true if `nodeID` has been explicitly set.
  var hasNodeID: Bool {return self._nodeID != nil}
  /// Clears the value of `nodeID`. Subsequent reads from it will return its default value.
  mutating func clearNodeID() {self._nodeID = nil}

  /// @optionset: GetAccessibilityTreeRequestFlags
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _nodeID: Sirius_Msgdef_SRUUID? = nil
}

//// Response to an accessibility tree request.
/// @opcode: 0x8102
struct Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Whether the request was processed successfully. False if rejected.
  var success: Bool = false

  //// Description of the rejection reason, if the request was rejected.
  var errorMessage: String {
    get {return _errorMessage ?? String()}
    set {_errorMessage = newValue}
  }
  /// Returns true if `errorMessage` has been explicitly set.
  var hasErrorMessage: Bool {return self._errorMessage != nil}
  /// Clears the value of `errorMessage`. Subsequent reads from it will return its default value.
  mutating func clearErrorMessage() {self._errorMessage = nil}

  //// The accessibility tree rooted at the requested node.
  //// This field MAY be empty if success is false.
  var rootNode: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode {
    get {return _rootNode ?? Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode()}
    set {_rootNode = newValue}
  }
  /// Returns true if `rootNode` has been explicitly set.
  var hasRootNode: Bool {return self._rootNode != nil}
  /// Clears the value of `rootNode`. Subsequent reads from it will return its default value.
  mutating func clearRootNode() {self._rootNode = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _errorMessage: String? = nil
  fileprivate var _rootNode: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode? = nil
}

//// Requests subscription to accessibility tree update events.
/// @opcode: 0x8103
struct Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// ID of the root node of the subtree to subscribe to.
  //// If omitted, updates for the entire tree of the current GUI session are subscribed.
  var nodeID: Sirius_Msgdef_SRUUID {
    get {return _nodeID ?? Sirius_Msgdef_SRUUID()}
    set {_nodeID = newValue}
  }
  /// Returns true if `nodeID` has been explicitly set.
  var hasNodeID: Bool {return self._nodeID != nil}
  /// Clears the value of `nodeID`. Subsequent reads from it will return its default value.
  mutating func clearNodeID() {self._nodeID = nil}

  //// Event type mask to subscribe to.
  //// If 0x0000, all event types are subscribed.
  /// @optionset: AccessibilityUpdateType
  var eventMask: UInt32 = 0

  //// Maximum depth of the subtree to subscribe to.
  //// If 0, all descendant nodes are subscribed without depth limit.
  //// If N > 0, only descendant nodes up to N levels from the specified node are subscribed.
  var maxDepth: UInt32 = 0

  /// @optionset: GetAccessibilityTreeRequestFlags
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _nodeID: Sirius_Msgdef_SRUUID? = nil
}

//// Response to a SubscribeAccessibilityTreeUpdatesRequest.
/// @opcode: 0x8104
struct Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Subscription identifier. Used for receiving events and unsubscribing.
  var subscriptionID: Sirius_Msgdef_SRUUID {
    get {return _subscriptionID ?? Sirius_Msgdef_SRUUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  //// Whether the subscription was set up successfully. False if rejected.
  var success: Bool = false

  //// Description of the rejection reason, if the subscription was rejected.
  var errorMessage: String {
    get {return _errorMessage ?? String()}
    set {_errorMessage = newValue}
  }
  /// Returns true if `errorMessage` has been explicitly set.
  var hasErrorMessage: Bool {return self._errorMessage != nil}
  /// Clears the value of `errorMessage`. Subsequent reads from it will return its default value.
  mutating func clearErrorMessage() {self._errorMessage = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_SRUUID? = nil
  fileprivate var _errorMessage: String? = nil
}

//// Unsubscribes from accessibility tree update events.
/// @opcode: 0x8105
struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Identifier of the subscription to cancel.
  var subscriptionID: Sirius_Msgdef_SRUUID {
    get {return _subscriptionID ?? Sirius_Msgdef_SRUUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_SRUUID? = nil
}

//// Response to an UnsubscribeAccessibilityTreeUpdatesRequest.
/// @opcode: 0x8106
struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Identifier of the cancelled subscription.
  var subscriptionID: Sirius_Msgdef_SRUUID {
    get {return _subscriptionID ?? Sirius_Msgdef_SRUUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  //// Whether the unsubscription was successful.
  var isSuccess: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_SRUUID? = nil
}

//// Accessibility tree change event.
/// @opcode: 0x8107
struct Sirius_Msgdef_V1_Channels_Projection_AccessibilityTreeUpdateEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Subscription identifier.
  var subscriptionID: Sirius_Msgdef_SRUUID {
    get {return _subscriptionID ?? Sirius_Msgdef_SRUUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  //// Event type code.
  /// @optionset: AccessibilityUpdateType
  var eventType: UInt32 = 0

  //// ID of the node targeted by this event.
  var nodeID: Sirius_Msgdef_SRUUID {
    get {return _nodeID ?? Sirius_Msgdef_SRUUID()}
    set {_nodeID = newValue}
  }
  /// Returns true if `nodeID` has been explicitly set.
  var hasNodeID: Bool {return self._nodeID != nil}
  /// Clears the value of `nodeID`. Subsequent reads from it will return its default value.
  mutating func clearNodeID() {self._nodeID = nil}

  //// Updated node information. This field is omitted for nodeRemoved events.
  var updatedNode: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode {
    get {return _updatedNode ?? Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode()}
    set {_updatedNode = newValue}
  }
  /// Returns true if `updatedNode` has been explicitly set.
  var hasUpdatedNode: Bool {return self._updatedNode != nil}
  /// Clears the value of `updatedNode`. Subsequent reads from it will return its default value.
  mutating func clearUpdatedNode() {self._updatedNode = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_SRUUID? = nil
  fileprivate var _nodeID: Sirius_Msgdef_SRUUID? = nil
  fileprivate var _updatedNode: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode? = nil
}

//// Requests an action to be performed on an accessibility node.
/// @opcode: 0x8108
struct Sirius_Msgdef_V1_Channels_Projection_DispatchActionRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// ID of the node on which to perform the action. (AccessibilityNode.id)
  var targetNodeID: Sirius_Msgdef_SRUUID {
    get {return _targetNodeID ?? Sirius_Msgdef_SRUUID()}
    set {_targetNodeID = newValue}
  }
  /// Returns true if `targetNodeID` has been explicitly set.
  var hasTargetNodeID: Bool {return self._targetNodeID != nil}
  /// Clears the value of `targetNodeID`. Subsequent reads from it will return its default value.
  mutating func clearTargetNodeID() {self._targetNodeID = nil}

  //// The type of action to perform.
  /// @constset: AccessibilityActionType
  var actionType: String = String()

  //// Additional value required for the action. e.g., textValue for text input, button index for click, etc.
  var value: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue {
    get {return _value ?? Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  var hasValue: Bool {return self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  mutating func clearValue() {self._value = nil}

  //// Additional arguments required for the action. e.g., "deltaX", "deltaY" for the scroll action.
  var args: Dictionary<String,String> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _targetNodeID: Sirius_Msgdef_SRUUID? = nil
  fileprivate var _value: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue? = nil
}

//// Response to a DispatchActionRequest.
/// @opcode: 0x8109
struct Sirius_Msgdef_V1_Channels_Projection_DispatchActionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Whether the action was performed successfully.
  var success: Bool = false

  //// Description of the failure reason, if the action failed.
  var errorMessage: String {
    get {return _errorMessage ?? String()}
    set {_errorMessage = newValue}
  }
  /// Returns true if `errorMessage` has been explicitly set.
  var hasErrorMessage: Bool {return self._errorMessage != nil}
  /// Clears the value of `errorMessage`. Subsequent reads from it will return its default value.
  mutating func clearErrorMessage() {self._errorMessage = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _errorMessage: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.projection"

extension Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AccessibilityNodeValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}textValue\0\u{1}boolValue\0\u{1}intValue\0\u{1}floatValue\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .textValue(v)
        }
      }()
      case 2: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .boolValue(v)
        }
      }()
      case 3: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .intValue(v)
        }
      }()
      case 4: try {
        var v: Float?
        try decoder.decodeSingularFloatField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .floatValue(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .textValue?: try {
      guard case .textValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .boolValue?: try {
      guard case .boolValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    }()
    case .intValue?: try {
      guard case .intValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    }()
    case .floatValue?: try {
      guard case .floatValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularFloatField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue, rhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AccessibilityNodeSnapshot"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mimeType\0\u{1}data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mimeType) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mimeType.isEmpty {
      try visitor.visitSingularStringField(value: self.mimeType, fieldNumber: 1)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot, rhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot) -> Bool {
    if lhs.mimeType != rhs.mimeType {return false}
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AccessibilityNode"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}parentId\0\u{1}role\0\u{1}hint\0\u{1}bounds\0\u{1}localBounds\0\u{1}description\0\u{1}value\0\u{2}\u{4}snapshot\0\u{1}attributes\0\u{1}metadata\0\u{1}children\0")

  fileprivate class _StorageClass {
    var _id: Sirius_Msgdef_SRUUID? = nil
    var _parentID: Sirius_Msgdef_SRUUID? = nil
    var _role: String = String()
    var _hint: UInt32 = 0
    var _bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect? = nil
    var _localBounds: Sirius_Msgdef_V1_Channels_Projection_SRRect? = nil
    var _description_p: String = String()
    var _value: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue? = nil
    var _snapshot: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot? = nil
    var _attributes: Dictionary<String,String> = [:]
    var _metadata: Dictionary<String,String> = [:]
    var _children: [Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _parentID = source._parentID
      _role = source._role
      _hint = source._hint
      _bounds = source._bounds
      _localBounds = source._localBounds
      _description_p = source._description_p
      _value = source._value
      _snapshot = source._snapshot
      _attributes = source._attributes
      _metadata = source._metadata
      _children = source._children
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._parentID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._role) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._hint) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._bounds) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._localBounds) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._value) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._snapshot) }()
        case 13: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._attributes) }()
        case 14: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._metadata) }()
        case 15: try { try decoder.decodeRepeatedMessageField(value: &_storage._children) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._id {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._parentID {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._role.isEmpty {
        try visitor.visitSingularStringField(value: _storage._role, fieldNumber: 3)
      }
      if _storage._hint != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._hint, fieldNumber: 4)
      }
      try { if let v = _storage._bounds {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._localBounds {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 7)
      }
      try { if let v = _storage._value {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._snapshot {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      if !_storage._attributes.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._attributes, fieldNumber: 13)
      }
      if !_storage._metadata.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._metadata, fieldNumber: 14)
      }
      if !_storage._children.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._children, fieldNumber: 15)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode, rhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._parentID != rhs_storage._parentID {return false}
        if _storage._role != rhs_storage._role {return false}
        if _storage._hint != rhs_storage._hint {return false}
        if _storage._bounds != rhs_storage._bounds {return false}
        if _storage._localBounds != rhs_storage._localBounds {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._value != rhs_storage._value {return false}
        if _storage._snapshot != rhs_storage._snapshot {return false}
        if _storage._attributes != rhs_storage._attributes {return false}
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._children != rhs_storage._children {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAccessibilityTreeRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}nodeId\0\u{2}\u{e}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._nodeID) }()
      case 16: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._nodeID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._nodeID != rhs._nodeID {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAccessibilityTreeResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}success\0\u{1}errorMessage\0\u{1}rootNode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._errorMessage) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._rootNode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    try { if let v = self._errorMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._rootNode {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.success != rhs.success {return false}
    if lhs._errorMessage != rhs._errorMessage {return false}
    if lhs._rootNode != rhs._rootNode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeAccessibilityTreeUpdatesRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}nodeId\0\u{1}eventMask\0\u{1}maxDepth\0\u{2}\u{c}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._nodeID) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.eventMask) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.maxDepth) }()
      case 16: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._nodeID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.eventMask != 0 {
      try visitor.visitSingularUInt32Field(value: self.eventMask, fieldNumber: 3)
    }
    if self.maxDepth != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxDepth, fieldNumber: 4)
    }
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._nodeID != rhs._nodeID {return false}
    if lhs.eventMask != rhs.eventMask {return false}
    if lhs.maxDepth != rhs.maxDepth {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeAccessibilityTreeUpdatesResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0\u{1}success\0\u{1}errorMessage\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._errorMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 3)
    }
    try { if let v = self._errorMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.success != rhs.success {return false}
    if lhs._errorMessage != rhs._errorMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeAccessibilityTreeUpdatesRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeAccessibilityTreeUpdatesResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0\u{1}isSuccess\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isSuccess) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.isSuccess != false {
      try visitor.visitSingularBoolField(value: self.isSuccess, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.isSuccess != rhs.isSuccess {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_AccessibilityTreeUpdateEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AccessibilityTreeUpdateEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}subscriptionId\0\u{1}eventType\0\u{1}nodeId\0\u{1}updatedNode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.eventType) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._nodeID) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._updatedNode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.eventType != 0 {
      try visitor.visitSingularUInt32Field(value: self.eventType, fieldNumber: 2)
    }
    try { if let v = self._nodeID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._updatedNode {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityTreeUpdateEvent, rhs: Sirius_Msgdef_V1_Channels_Projection_AccessibilityTreeUpdateEvent) -> Bool {
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.eventType != rhs.eventType {return false}
    if lhs._nodeID != rhs._nodeID {return false}
    if lhs._updatedNode != rhs._updatedNode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DispatchActionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DispatchActionRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}targetNodeId\0\u{1}actionType\0\u{1}value\0\u{1}args\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._targetNodeID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.actionType) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.args) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._targetNodeID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.actionType.isEmpty {
      try visitor.visitSingularStringField(value: self.actionType, fieldNumber: 3)
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.args.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.args, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DispatchActionRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_DispatchActionRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._targetNodeID != rhs._targetNodeID {return false}
    if lhs.actionType != rhs.actionType {return false}
    if lhs._value != rhs._value {return false}
    if lhs.args != rhs.args {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DispatchActionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DispatchActionResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}success\0\u{1}errorMessage\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._errorMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    try { if let v = self._errorMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DispatchActionResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_DispatchActionResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.success != rhs.success {return false}
    if lhs._errorMessage != rhs._errorMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
