// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/projection/projection_codec.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

internal import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// 자동 품질 모드 (서버가 네트워크 상태에 따라 자동 조절)
struct Sirius_Msgdef_V1_Channels_Projection_AutoQuality: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// @constset: AutoQualityMode
  var mode: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 상수 비트레이트 (CBR) 품질 설정
struct Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 비트레이트 (kbps)
  var bitrateKbps: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 가변 비트레이트 (VBR) 품질 설정
struct Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 최대 비트레이트 (kbps)
  var maxBitrateKbps: Int32 = 0

  //// 타겟 비트레이트 (kbps)
  var targetBitrateKbps: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 고정 품질 (CQP/CRF) 설정
//// - 0부터 100까지의 값으로 품질을 지정합니다.
//// - 값이 낮을수록 더 높은 품질을 나타낼 수도 있고, 반대일 수도 있으나 일반적으로 100이 최고 품질입니다. (구현체 의존적)
struct Sirius_Msgdef_V1_Channels_Projection_FixedQuality: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var quality: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 무손실 품질 설정
//// - 무손실 압축을 사용하여 품질 저하 없이 데이터를 전송합니다.
struct Sirius_Msgdef_V1_Channels_Projection_LosslessQuality: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// @constset: LosslessQualityMode
  var mode: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 비디오 코덱 설정 메시지
struct Sirius_Msgdef_V1_Channels_Projection_Codec: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// FourCC 코드값 (Big-Endian)
  /// @constset: CodecFourCC
  var fourCc: UInt32 = 0

  //// 코덱 품질 설정
  var quality: Sirius_Msgdef_V1_Channels_Projection_Codec.OneOf_Quality? = nil

  var constantBitrate: Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality {
    get {
      if case .constantBitrate(let v)? = quality {return v}
      return Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality()
    }
    set {quality = .constantBitrate(newValue)}
  }

  var variableBitrate: Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality {
    get {
      if case .variableBitrate(let v)? = quality {return v}
      return Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality()
    }
    set {quality = .variableBitrate(newValue)}
  }

  var fixedQuality: Sirius_Msgdef_V1_Channels_Projection_FixedQuality {
    get {
      if case .fixedQuality(let v)? = quality {return v}
      return Sirius_Msgdef_V1_Channels_Projection_FixedQuality()
    }
    set {quality = .fixedQuality(newValue)}
  }

  var lossless: Sirius_Msgdef_V1_Channels_Projection_LosslessQuality {
    get {
      if case .lossless(let v)? = quality {return v}
      return Sirius_Msgdef_V1_Channels_Projection_LosslessQuality()
    }
    set {quality = .lossless(newValue)}
  }

  var auto: Sirius_Msgdef_V1_Channels_Projection_AutoQuality {
    get {
      if case .auto(let v)? = quality {return v}
      return Sirius_Msgdef_V1_Channels_Projection_AutoQuality()
    }
    set {quality = .auto(newValue)}
  }

  //// 초당 프레임 수. 값을 -1로 설정하는 경우 소스 (모니터)의 프레임레이트를 따릅니다.
  var frameRate: Float {
    get {return _frameRate ?? 0}
    set {_frameRate = newValue}
  }
  /// Returns true if `frameRate` has been explicitly set.
  var hasFrameRate: Bool {return self._frameRate != nil}
  /// Clears the value of `frameRate`. Subsequent reads from it will return its default value.
  mutating func clearFrameRate() {self._frameRate = nil}

  //// 해상도
  var size: Sirius_Msgdef_V1_Channels_Projection_SRSize {
    get {return _size ?? Sirius_Msgdef_V1_Channels_Projection_SRSize()}
    set {_size = newValue}
  }
  /// Returns true if `size` has been explicitly set.
  var hasSize: Bool {return self._size != nil}
  /// Clears the value of `size`. Subsequent reads from it will return its default value.
  mutating func clearSize() {self._size = nil}

  //// 코덱별 추가 옵션 문자열 (예: "color-format: 'YUV444'; hardware-acceleration: 'true'; profile: 'high';")
  var options: String {
    get {return _options ?? String()}
    set {_options = newValue}
  }
  /// Returns true if `options` has been explicitly set.
  var hasOptions: Bool {return self._options != nil}
  /// Clears the value of `options`. Subsequent reads from it will return its default value.
  mutating func clearOptions() {self._options = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  //// 코덱 품질 설정
  enum OneOf_Quality: Equatable, Sendable {
    case constantBitrate(Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality)
    case variableBitrate(Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality)
    case fixedQuality(Sirius_Msgdef_V1_Channels_Projection_FixedQuality)
    case lossless(Sirius_Msgdef_V1_Channels_Projection_LosslessQuality)
    case auto(Sirius_Msgdef_V1_Channels_Projection_AutoQuality)

  }

  init() {}

  fileprivate var _frameRate: Float? = nil
  fileprivate var _size: Sirius_Msgdef_V1_Channels_Projection_SRSize? = nil
  fileprivate var _options: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.projection"

extension Sirius_Msgdef_V1_Channels_Projection_AutoQuality: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AutoQuality"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.mode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.mode != 0 {
      try visitor.visitSingularUInt32Field(value: self.mode, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_AutoQuality, rhs: Sirius_Msgdef_V1_Channels_Projection_AutoQuality) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConstantBitrateQuality"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bitrateKbps\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.bitrateKbps) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bitrateKbps != 0 {
      try visitor.visitSingularInt32Field(value: self.bitrateKbps, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality, rhs: Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality) -> Bool {
    if lhs.bitrateKbps != rhs.bitrateKbps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".VariableBitrateQuality"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}maxBitrateKbps\0\u{1}targetBitrateKbps\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.maxBitrateKbps) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.targetBitrateKbps) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.maxBitrateKbps != 0 {
      try visitor.visitSingularInt32Field(value: self.maxBitrateKbps, fieldNumber: 1)
    }
    if self.targetBitrateKbps != 0 {
      try visitor.visitSingularInt32Field(value: self.targetBitrateKbps, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality, rhs: Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality) -> Bool {
    if lhs.maxBitrateKbps != rhs.maxBitrateKbps {return false}
    if lhs.targetBitrateKbps != rhs.targetBitrateKbps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_FixedQuality: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FixedQuality"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}quality\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.quality) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.quality != 0 {
      try visitor.visitSingularInt32Field(value: self.quality, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_FixedQuality, rhs: Sirius_Msgdef_V1_Channels_Projection_FixedQuality) -> Bool {
    if lhs.quality != rhs.quality {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_LosslessQuality: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LosslessQuality"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.mode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.mode != 0 {
      try visitor.visitSingularUInt32Field(value: self.mode, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_LosslessQuality, rhs: Sirius_Msgdef_V1_Channels_Projection_LosslessQuality) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_Codec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Codec"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fourCC\0\u{1}constantBitrate\0\u{1}variableBitrate\0\u{1}fixedQuality\0\u{1}lossless\0\u{1}auto\0\u{2}\u{3}frameRate\0\u{1}size\0\u{2}\u{5}options\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.fourCc) }()
      case 2: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_ConstantBitrateQuality?
        var hadOneofValue = false
        if let current = self.quality {
          hadOneofValue = true
          if case .constantBitrate(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.quality = .constantBitrate(v)
        }
      }()
      case 3: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_VariableBitrateQuality?
        var hadOneofValue = false
        if let current = self.quality {
          hadOneofValue = true
          if case .variableBitrate(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.quality = .variableBitrate(v)
        }
      }()
      case 4: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_FixedQuality?
        var hadOneofValue = false
        if let current = self.quality {
          hadOneofValue = true
          if case .fixedQuality(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.quality = .fixedQuality(v)
        }
      }()
      case 5: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_LosslessQuality?
        var hadOneofValue = false
        if let current = self.quality {
          hadOneofValue = true
          if case .lossless(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.quality = .lossless(v)
        }
      }()
      case 6: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_AutoQuality?
        var hadOneofValue = false
        if let current = self.quality {
          hadOneofValue = true
          if case .auto(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.quality = .auto(v)
        }
      }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self._frameRate) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._size) }()
      case 15: try { try decoder.decodeSingularStringField(value: &self._options) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.fourCc != 0 {
      try visitor.visitSingularFixed32Field(value: self.fourCc, fieldNumber: 1)
    }
    switch self.quality {
    case .constantBitrate?: try {
      guard case .constantBitrate(let v)? = self.quality else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .variableBitrate?: try {
      guard case .variableBitrate(let v)? = self.quality else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .fixedQuality?: try {
      guard case .fixedQuality(let v)? = self.quality else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .lossless?: try {
      guard case .lossless(let v)? = self.quality else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .auto?: try {
      guard case .auto(let v)? = self.quality else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try { if let v = self._frameRate {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._size {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._options {
      try visitor.visitSingularStringField(value: v, fieldNumber: 15)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_Codec, rhs: Sirius_Msgdef_V1_Channels_Projection_Codec) -> Bool {
    if lhs.fourCc != rhs.fourCc {return false}
    if lhs.quality != rhs.quality {return false}
    if lhs._frameRate != rhs._frameRate {return false}
    if lhs._size != rhs._size {return false}
    if lhs._options != rhs._options {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
