// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/projection/winman_query.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
internal import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// 단일 윈도우 필터 조건
struct Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// @constset: WindowFilterExpressionOperator
  var `operator`: UInt32 = 0

  var invert: Bool = false

  var field: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression.OneOf_Field? = nil

  //// 윈도우 핸들 ID로 매칭합니다.
  //// OS / DM에 따라 윈도우 핸들 ID의 크기가 다를 수 있으므로 uint64 타입을 사용합니다.
  var windowID: UInt64 {
    get {
      if case .windowID(let v)? = field {return v}
      return 0
    }
    set {field = .windowID(newValue)}
  }

  //// 프로세스 ID로 매칭합니다.
  var pid: UInt64 {
    get {
      if case .pid(let v)? = field {return v}
      return 0
    }
    set {field = .pid(newValue)}
  }

  //// 윈도우 타이틀로 매칭합니다.
  var windowTitle: String {
    get {
      if case .windowTitle(let v)? = field {return v}
      return String()
    }
    set {field = .windowTitle(newValue)}
  }

  //// 애플리케이션 이름(실행 파일 이름)으로 매칭합니다.
  //// 플랫폼별 차이:
  //// - Windows: 실행 파일 이름 (예: "chrome.exe")
  //// - macOS / Linux: 프로세스 이름 (ARGV[0]). 전체 경로일 수도 있고,
  ////   단순 실행 파일 이름일 수도 있습니다.
  var applicationName: String {
    get {
      if case .applicationName(let v)? = field {return v}
      return String()
    }
    set {field = .applicationName(newValue)}
  }

  //// 번들 ID로 매칭합니다.
  //// 의미는 서버 구현체에 따라 다를 수 있습니다.
  //// (예: macOS "com.apple.Safari", Android "com.google.android.youtube")
  var applicationBundleID: String {
    get {
      if case .applicationBundleID(let v)? = field {return v}
      return String()
    }
    set {field = .applicationBundleID(newValue)}
  }

  //// 윈도우 클래스 이름으로 매칭합니다.
  //// macOS는 클래스 이름을 지원하지 않으므로 이 필드는 무시될 수 있습니다.
  var windowClass: String {
    get {
      if case .windowClass(let v)? = field {return v}
      return String()
    }
    set {field = .windowClass(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Field: Equatable, Sendable {
    //// 윈도우 핸들 ID로 매칭합니다.
    //// OS / DM에 따라 윈도우 핸들 ID의 크기가 다를 수 있으므로 uint64 타입을 사용합니다.
    case windowID(UInt64)
    //// 프로세스 ID로 매칭합니다.
    case pid(UInt64)
    //// 윈도우 타이틀로 매칭합니다.
    case windowTitle(String)
    //// 애플리케이션 이름(실행 파일 이름)으로 매칭합니다.
    //// 플랫폼별 차이:
    //// - Windows: 실행 파일 이름 (예: "chrome.exe")
    //// - macOS / Linux: 프로세스 이름 (ARGV[0]). 전체 경로일 수도 있고,
    ////   단순 실행 파일 이름일 수도 있습니다.
    case applicationName(String)
    //// 번들 ID로 매칭합니다.
    //// 의미는 서버 구현체에 따라 다를 수 있습니다.
    //// (예: macOS "com.apple.Safari", Android "com.google.android.youtube")
    case applicationBundleID(String)
    //// 윈도우 클래스 이름으로 매칭합니다.
    //// macOS는 클래스 이름을 지원하지 않으므로 이 필드는 무시될 수 있습니다.
    case windowClass(String)

  }

  init() {}
}

//// 윈도우 필터 (재귀적 트리 구조)
struct Sirius_Msgdef_V1_Channels_Projection_WindowFilter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// @constset: WindowFilterOperator
  var `operator`: UInt32 = 0

  //// 조건들의 목록 (재귀적 구조로 복합 조건을 표현할 수 있음)
  //// 예: (A OR B) AND C
  var expressions: [Sirius_Msgdef_V1_Channels_Projection_WindowFilter] = []

  //// 단일 조건 (리프 노드)
  var expression: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression {
    get {return _expression ?? Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression()}
    set {_expression = newValue}
  }
  /// Returns true if `expression` has been explicitly set.
  var hasExpression: Bool {return self._expression != nil}
  /// Clears the value of `expression`. Subsequent reads from it will return its default value.
  mutating func clearExpression() {self._expression = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _expression: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression? = nil
}

//// 윈도우의 상세 정보
struct Sirius_Msgdef_V1_Channels_Projection_WindowInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var windowID: UInt64 {
    get {return _storage._windowID}
    set {_uniqueStorage()._windowID = newValue}
  }

  var pid: UInt64 {
    get {return _storage._pid}
    set {_uniqueStorage()._pid = newValue}
  }

  var windowTitle: String {
    get {return _storage._windowTitle}
    set {_uniqueStorage()._windowTitle = newValue}
  }

  var applicationName: String {
    get {return _storage._applicationName}
    set {_uniqueStorage()._applicationName = newValue}
  }

  var applicationBundleID: String {
    get {return _storage._applicationBundleID}
    set {_uniqueStorage()._applicationBundleID = newValue}
  }

  var windowClass: String {
    get {return _storage._windowClass}
    set {_uniqueStorage()._windowClass = newValue}
  }

  /// @constset: WindowRole
  var role: UInt32 {
    get {return _storage._role}
    set {_uniqueStorage()._role = newValue}
  }

  var bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect {
    get {return _storage._bounds ?? Sirius_Msgdef_V1_Channels_Projection_SRRect()}
    set {_uniqueStorage()._bounds = newValue}
  }
  /// Returns true if `bounds` has been explicitly set.
  var hasBounds: Bool {return _storage._bounds != nil}
  /// Clears the value of `bounds`. Subsequent reads from it will return its default value.
  mutating func clearBounds() {_uniqueStorage()._bounds = nil}

  //// 이 윈도우의 아이콘 해시값.
  var iconHash: UInt64 {
    get {return _storage._iconHash ?? 0}
    set {_uniqueStorage()._iconHash = newValue}
  }
  /// Returns true if `iconHash` has been explicitly set.
  var hasIconHash: Bool {return _storage._iconHash != nil}
  /// Clears the value of `iconHash`. Subsequent reads from it will return its default value.
  mutating func clearIconHash() {_uniqueStorage()._iconHash = nil}

  var parentWindowID: UInt64 {
    get {return _storage._parentWindowID ?? 0}
    set {_uniqueStorage()._parentWindowID = newValue}
  }
  /// Returns true if `parentWindowID` has been explicitly set.
  var hasParentWindowID: Bool {return _storage._parentWindowID != nil}
  /// Clears the value of `parentWindowID`. Subsequent reads from it will return its default value.
  mutating func clearParentWindowID() {_uniqueStorage()._parentWindowID = nil}

  //// 이 윈도우의 섬네일 이미지 (PNG8 (with alpha channel) 형식, aspect ratio 유지, 최대 512x512)
  var thumbnail: Data {
    get {return _storage._thumbnail ?? Data()}
    set {_uniqueStorage()._thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  var hasThumbnail: Bool {return _storage._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  mutating func clearThumbnail() {_uniqueStorage()._thumbnail = nil}

  //// 추가 메타데이터
  //// 모든 메타데이터 키는 optional입니다. 모든 서버 구현체가 이를 반드시 지원한다는 보장은 없고,
  //// 모든 키가 항상 제공되는 것도 아닙니다.
  //// 구현체-specific 메타데이터 키는 reversed domain name 형식을 따르십시오.
  //// (예: "com.contoso.superremote.virtual-display-purpose" 등)
  var metadata: Dictionary<String,String> {
    get {return _storage._metadata}
    set {_uniqueStorage()._metadata = newValue}
  }

  //// 윈도우 힌트
  /// @optionset: WindowHint
  var hints: UInt32 {
    get {return _storage._hints}
    set {_uniqueStorage()._hints = newValue}
  }

  //// 윈도우 상태 플래그
  /// @optionset: WindowInfoFlags
  var flags: UInt32 {
    get {return _storage._flags}
    set {_uniqueStorage()._flags = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

//// 윈도우 목록을 요청합니다.
/// @opcode: 0x8061
struct Sirius_Msgdef_V1_Channels_Projection_WindowListRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 필터 조건
  var filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter {
    get {return _filter ?? Sirius_Msgdef_V1_Channels_Projection_WindowFilter()}
    set {_filter = newValue}
  }
  /// Returns true if `filter` has been explicitly set.
  var hasFilter: Bool {return self._filter != nil}
  /// Clears the value of `filter`. Subsequent reads from it will return its default value.
  mutating func clearFilter() {self._filter = nil}

  //// 윈도우 목록 요청 플래그
  /// @optionset: WindowListRequestFlags
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter? = nil
}

//// 윈도우 목록 요청에 대한 응답입니다.
/// @opcode: 0x8062
struct Sirius_Msgdef_V1_Channels_Projection_WindowListResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windows: [Sirius_Msgdef_V1_Channels_Projection_WindowInfo] = []

  //// 페이지네이션 된 결과의 마지막 페이지인지 여부
  var isLastPage: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 특정 윈도우의 상세 정보를 요청합니다.
/// @opcode: 0x8063
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 특정 윈도우 정보 요청에 대한 응답입니다.
/// @opcode: 0x8064
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo {
    get {return _info ?? Sirius_Msgdef_V1_Channels_Projection_WindowInfo()}
    set {_info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  var hasInfo: Bool {return self._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  mutating func clearInfo() {self._info = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo? = nil
}

//// 특정 윈도우의 아이콘을 요청합니다.
/// @opcode: 0x8065
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 윈도우 아이콘 요청에 대한 응답입니다.
/// @opcode: 0x8066
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  //// 이 윈도우의 아이콘 이미지 (PNG8 (with alpha channel) 형식, 정사각형, 최대 256x256)
  var icon: Data {
    get {return _icon ?? Data()}
    set {_icon = newValue}
  }
  /// Returns true if `icon` has been explicitly set.
  var hasIcon: Bool {return self._icon != nil}
  /// Clears the value of `icon`. Subsequent reads from it will return its default value.
  mutating func clearIcon() {self._icon = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _icon: Data? = nil
}

//// 특정 윈도우의 섬네일을 요청합니다.
/// @opcode: 0x8067
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 윈도우 섬네일 요청에 대한 응답입니다.
/// @opcode: 0x8068
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  //// 이 윈도우의 섬네일 이미지 (PNG8 (with alpha channel) 형식, aspect ratio 유지, 최대 512x512)
  var thumbnail: Data {
    get {return _thumbnail ?? Data()}
    set {_thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  var hasThumbnail: Bool {return self._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  mutating func clearThumbnail() {self._thumbnail = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _thumbnail: Data? = nil
}

//// 윈도우 변경 이벤트를 구독합니다.
/// @opcode: 0x8069
struct Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 0x0000인 경우 모든 이벤트를 구독합니다.
  /// @optionset: WindowChangeEventType
  var eventMask: UInt32 = 0

  //// 비어있는 경우 모든 윈도우에 대한 이벤트를 구독합니다.
  var filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter {
    get {return _filter ?? Sirius_Msgdef_V1_Channels_Projection_WindowFilter()}
    set {_filter = newValue}
  }
  /// Returns true if `filter` has been explicitly set.
  var hasFilter: Bool {return self._filter != nil}
  /// Clears the value of `filter`. Subsequent reads from it will return its default value.
  mutating func clearFilter() {self._filter = nil}

  /// @optionset: WindowEventSubscriptionFlags
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter? = nil
}

//// 윈도우 이벤트 구독 요청에 대한 응답입니다.
/// @opcode: 0x806A
struct Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_SRUUID {
    get {return _subscriptionID ?? Sirius_Msgdef_SRUUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_SRUUID? = nil
}

//// 윈도우 변경 이벤트 구독을 해제합니다.
/// @opcode: 0x806B
struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_SRUUID {
    get {return _subscriptionID ?? Sirius_Msgdef_SRUUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_SRUUID? = nil
}

//// 윈도우 이벤트 구독 해제 요청에 대한 응답입니다.
/// @opcode: 0x806C
struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_SRUUID {
    get {return _subscriptionID ?? Sirius_Msgdef_SRUUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  //// 구독 해제 성공 여부.
  var isSuccess: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_SRUUID? = nil
}

//// 윈도우 변경 이벤트입니다.
/// @opcode: 0x806D
struct Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 이벤트 유형 코드
  /// @optionset: WindowChangeEventType
  var eventType: UInt32 = 0

  var windowID: UInt64 = 0

  //// 변경된 윈도우 정보
  var info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo {
    get {return _info ?? Sirius_Msgdef_V1_Channels_Projection_WindowInfo()}
    set {_info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  var hasInfo: Bool {return self._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  mutating func clearInfo() {self._info = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.projection"

extension Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowFilterExpression"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}operator\0\u{1}invert\0\u{1}windowId\0\u{1}pid\0\u{1}windowTitle\0\u{1}applicationName\0\u{1}applicationBundleId\0\u{1}windowClass\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.`operator`) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.invert) }()
      case 3: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .windowID(v)
        }
      }()
      case 4: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .pid(v)
        }
      }()
      case 5: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .windowTitle(v)
        }
      }()
      case 6: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .applicationName(v)
        }
      }()
      case 7: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .applicationBundleID(v)
        }
      }()
      case 8: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .windowClass(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.`operator` != 0 {
      try visitor.visitSingularUInt32Field(value: self.`operator`, fieldNumber: 1)
    }
    if self.invert != false {
      try visitor.visitSingularBoolField(value: self.invert, fieldNumber: 2)
    }
    switch self.field {
    case .windowID?: try {
      guard case .windowID(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 3)
    }()
    case .pid?: try {
      guard case .pid(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
    }()
    case .windowTitle?: try {
      guard case .windowTitle(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    }()
    case .applicationName?: try {
      guard case .applicationName(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    }()
    case .applicationBundleID?: try {
      guard case .applicationBundleID(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    }()
    case .windowClass?: try {
      guard case .windowClass(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression) -> Bool {
    if lhs.`operator` != rhs.`operator` {return false}
    if lhs.invert != rhs.invert {return false}
    if lhs.field != rhs.field {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowFilter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowFilter"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}operator\0\u{1}expressions\0\u{1}expression\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.`operator`) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.expressions) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._expression) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.`operator` != 0 {
      try visitor.visitSingularUInt32Field(value: self.`operator`, fieldNumber: 1)
    }
    if !self.expressions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.expressions, fieldNumber: 2)
    }
    try { if let v = self._expression {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilter, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilter) -> Bool {
    if lhs.`operator` != rhs.`operator` {return false}
    if lhs.expressions != rhs.expressions {return false}
    if lhs._expression != rhs._expression {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}windowId\0\u{1}pid\0\u{1}windowTitle\0\u{1}applicationName\0\u{1}applicationBundleId\0\u{1}windowClass\0\u{1}role\0\u{1}bounds\0\u{1}iconHash\0\u{1}parentWindowId\0\u{2}\u{2}thumbnail\0\u{1}metadata\0\u{1}hints\0\u{1}flags\0")

  fileprivate class _StorageClass {
    var _windowID: UInt64 = 0
    var _pid: UInt64 = 0
    var _windowTitle: String = String()
    var _applicationName: String = String()
    var _applicationBundleID: String = String()
    var _windowClass: String = String()
    var _role: UInt32 = 0
    var _bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect? = nil
    var _iconHash: UInt64? = nil
    var _parentWindowID: UInt64? = nil
    var _thumbnail: Data? = nil
    var _metadata: Dictionary<String,String> = [:]
    var _hints: UInt32 = 0
    var _flags: UInt32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _windowID = source._windowID
      _pid = source._pid
      _windowTitle = source._windowTitle
      _applicationName = source._applicationName
      _applicationBundleID = source._applicationBundleID
      _windowClass = source._windowClass
      _role = source._role
      _bounds = source._bounds
      _iconHash = source._iconHash
      _parentWindowID = source._parentWindowID
      _thumbnail = source._thumbnail
      _metadata = source._metadata
      _hints = source._hints
      _flags = source._flags
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._windowID) }()
        case 2: try { try decoder.decodeSingularUInt64Field(value: &_storage._pid) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._windowTitle) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._applicationName) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._applicationBundleID) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._windowClass) }()
        case 7: try { try decoder.decodeSingularUInt32Field(value: &_storage._role) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._bounds) }()
        case 9: try { try decoder.decodeSingularFixed64Field(value: &_storage._iconHash) }()
        case 10: try { try decoder.decodeSingularUInt64Field(value: &_storage._parentWindowID) }()
        case 12: try { try decoder.decodeSingularBytesField(value: &_storage._thumbnail) }()
        case 13: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._metadata) }()
        case 14: try { try decoder.decodeSingularUInt32Field(value: &_storage._hints) }()
        case 15: try { try decoder.decodeSingularUInt32Field(value: &_storage._flags) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._windowID != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._windowID, fieldNumber: 1)
      }
      if _storage._pid != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._pid, fieldNumber: 2)
      }
      if !_storage._windowTitle.isEmpty {
        try visitor.visitSingularStringField(value: _storage._windowTitle, fieldNumber: 3)
      }
      if !_storage._applicationName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._applicationName, fieldNumber: 4)
      }
      if !_storage._applicationBundleID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._applicationBundleID, fieldNumber: 5)
      }
      if !_storage._windowClass.isEmpty {
        try visitor.visitSingularStringField(value: _storage._windowClass, fieldNumber: 6)
      }
      if _storage._role != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._role, fieldNumber: 7)
      }
      try { if let v = _storage._bounds {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._iconHash {
        try visitor.visitSingularFixed64Field(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._parentWindowID {
        try visitor.visitSingularUInt64Field(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._thumbnail {
        try visitor.visitSingularBytesField(value: v, fieldNumber: 12)
      } }()
      if !_storage._metadata.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._metadata, fieldNumber: 13)
      }
      if _storage._hints != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._hints, fieldNumber: 14)
      }
      if _storage._flags != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._flags, fieldNumber: 15)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowInfo, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._windowID != rhs_storage._windowID {return false}
        if _storage._pid != rhs_storage._pid {return false}
        if _storage._windowTitle != rhs_storage._windowTitle {return false}
        if _storage._applicationName != rhs_storage._applicationName {return false}
        if _storage._applicationBundleID != rhs_storage._applicationBundleID {return false}
        if _storage._windowClass != rhs_storage._windowClass {return false}
        if _storage._role != rhs_storage._role {return false}
        if _storage._bounds != rhs_storage._bounds {return false}
        if _storage._iconHash != rhs_storage._iconHash {return false}
        if _storage._parentWindowID != rhs_storage._parentWindowID {return false}
        if _storage._thumbnail != rhs_storage._thumbnail {return false}
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._hints != rhs_storage._hints {return false}
        if _storage._flags != rhs_storage._flags {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowListRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowListRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}filter\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._filter) }()
      case 15: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._filter {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowListRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowListRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._filter != rhs._filter {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowListResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windows\0\u{1}isLastPage\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.windows) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isLastPage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if !self.windows.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.windows, fieldNumber: 2)
    }
    if self.isLastPage != false {
      try visitor.visitSingularBoolField(value: self.isLastPage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowListResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowListResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windows != rhs.windows {return false}
    if lhs.isLastPage != rhs.isLastPage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowInfoRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.windowID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularUInt64Field(value: self.windowID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowInfoResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._info) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._info {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._info != rhs._info {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowIconRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.windowID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularUInt64Field(value: self.windowID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowIconResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0\u{1}icon\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.windowID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._icon) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularUInt64Field(value: self.windowID, fieldNumber: 2)
    }
    try { if let v = self._icon {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs._icon != rhs._icon {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowThumbnailRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.windowID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularUInt64Field(value: self.windowID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowThumbnailResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0\u{1}thumbnail\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.windowID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._thumbnail) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularUInt64Field(value: self.windowID, fieldNumber: 2)
    }
    try { if let v = self._thumbnail {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs._thumbnail != rhs._thumbnail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeWindowEventsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}eventMask\0\u{1}filter\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.eventMask) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._filter) }()
      case 16: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.eventMask != 0 {
      try visitor.visitSingularUInt32Field(value: self.eventMask, fieldNumber: 2)
    }
    try { if let v = self._filter {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.eventMask != rhs.eventMask {return false}
    if lhs._filter != rhs._filter {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeWindowEventsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeWindowEventsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeWindowEventsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0\u{1}isSuccess\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isSuccess) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.isSuccess != false {
      try visitor.visitSingularBoolField(value: self.isSuccess, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.isSuccess != rhs.isSuccess {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowChangedEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}eventType\0\u{1}windowId\0\u{1}info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.eventType) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.windowID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._info) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.eventType != 0 {
      try visitor.visitSingularUInt32Field(value: self.eventType, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularUInt64Field(value: self.windowID, fieldNumber: 2)
    }
    try { if let v = self._info {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent) -> Bool {
    if lhs.eventType != rhs.eventType {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs._info != rhs._info {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
