//
//  accessibility+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius-swift. DO NOT EDIT.
//

import Foundation
internal import SwiftProtobuf

public extension MessageOpcode {
    static let getAccessibilityTreeRequest: MessageOpcode = MessageOpcode(rawValue: 0x8101)
    static let getAccessibilityTreeResponse: MessageOpcode = MessageOpcode(rawValue: 0x8102)
    static let subscribeAccessibilityTreeUpdatesRequest: MessageOpcode = MessageOpcode(rawValue: 0x8103)
    static let subscribeAccessibilityTreeUpdatesResponse: MessageOpcode = MessageOpcode(rawValue: 0x8104)
    static let unsubscribeAccessibilityTreeUpdatesRequest: MessageOpcode = MessageOpcode(rawValue: 0x8105)
    static let unsubscribeAccessibilityTreeUpdatesResponse: MessageOpcode = MessageOpcode(rawValue: 0x8106)
    static let accessibilityTreeUpdateEvent: MessageOpcode = MessageOpcode(rawValue: 0x8107)
    static let dispatchActionRequest: MessageOpcode = MessageOpcode(rawValue: 0x8108)
    static let dispatchActionResponse: MessageOpcode = MessageOpcode(rawValue: 0x8109)
}

public struct AccessibilityNodeValue: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeValue

    public enum Value: Sendable {
        case textValue(String)
        case boolValue(Bool)
        case intValue(Int64)
        case floatValue(Float)
        case none
    }

    public let value: Value

    public init(value: Value) {
        self.value = value
    }

    init(from protobuf: ProtobufMessage) throws {
        switch protobuf.value {
        case .textValue(let v):
            self.value = .textValue(v)
        case .boolValue(let v):
            self.value = .boolValue(v)
        case .intValue(let v):
            self.value = .intValue(v)
        case .floatValue(let v):
            self.value = .floatValue(v)
        case .none:
            self.value = .none
        }
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        switch self.value {
        case .textValue(let val):
            message.value = .textValue(val)
        case .boolValue(let val):
            message.value = .boolValue(val)
        case .intValue(let val):
            message.value = .intValue(val)
        case .floatValue(let val):
            message.value = .floatValue(val)
        case .none:
            break
        }

        return message
    }
}

public struct AccessibilityNodeSnapshot: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_AccessibilityNodeSnapshot

    public let mimeType: String
    public let data: Data

    public init(mimeType: String, data: Data) {
        self.mimeType = mimeType
        self.data = data
    }

    init(from protobuf: ProtobufMessage) throws {
        self.mimeType = protobuf.mimeType
        self.data = protobuf.data
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.mimeType = mimeType
        message.data = data

        return message
    }
}

public struct AccessibilityNode: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_AccessibilityNode

    public let id: UUID
    public let parentId: UUID?
    public let role: AccessibilityNodeRole
    public let hint: AccessibilityNodeHint
    public let bounds: SRRect
    public let localBounds: SRRect?
    public let description: String
    public let value: AccessibilityNodeValue?
    public let snapshot: AccessibilityNodeSnapshot?
    public let attributes: [String: String]
    public let metadata: [String: String]
    public let children: [AccessibilityNode]

    public init(
        id: UUID,
        parentId: UUID?,
        role: AccessibilityNodeRole,
        hint: AccessibilityNodeHint,
        bounds: SRRect,
        localBounds: SRRect?,
        description: String,
        value: AccessibilityNodeValue?,
        snapshot: AccessibilityNodeSnapshot?,
        attributes: [String: String],
        metadata: [String: String],
        children: [AccessibilityNode]
    ) {
        self.id = id
        self.parentId = parentId
        self.role = role
        self.hint = hint
        self.bounds = bounds
        self.localBounds = localBounds
        self.description = description
        self.value = value
        self.snapshot = snapshot
        self.attributes = attributes
        self.metadata = metadata
        self.children = children
    }

    init(from protobuf: ProtobufMessage) throws {
        self.id = UUID(msgdef: protobuf.id)
        self.parentId = protobuf.hasParentID ? UUID(msgdef: protobuf.parentID) : nil
        self.role = AccessibilityNodeRole(rawValue: protobuf.role)
        self.hint = AccessibilityNodeHint(rawValue: protobuf.hint)
        self.bounds = SRRect(from: protobuf.bounds)
        self.localBounds = protobuf.hasLocalBounds ? SRRect(from: protobuf.localBounds) : nil
        self.description = protobuf.description_p
        self.value = protobuf.hasValue ? try AccessibilityNodeValue(from: protobuf.value) : nil
        self.snapshot = protobuf.hasSnapshot ? try AccessibilityNodeSnapshot(from: protobuf.snapshot) : nil
        self.attributes = protobuf.attributes
        self.metadata = protobuf.metadata
        self.children = try protobuf.children.map { try AccessibilityNode(from: $0) }
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.id = id.asMsgDef()
        if let val = self.parentId {
            message.parentID = val.asMsgDef()
        }
        message.role = role.rawValue
        message.hint = hint.rawValue
        message.bounds = bounds.toProtobufMessage()
        if let val = self.localBounds {
            message.localBounds = val.toProtobufMessage()
        }
        message.description_p = description
        if let val = self.value {
            message.value = val.toProtobufMessage()
        }
        if let val = self.snapshot {
            message.snapshot = val.toProtobufMessage()
        }
        message.attributes = attributes
        message.metadata = metadata
        message.children = children.map { $0.toProtobufMessage() }

        return message
    }
}

public struct GetAccessibilityTreeRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeRequest

    public let requestId: UInt64
    public let nodeId: UUID?
    public let flags: GetAccessibilityTreeRequestFlags

    public init(requestId: UInt64, nodeId: UUID?, flags: GetAccessibilityTreeRequestFlags) {
        self.requestId = requestId
        self.nodeId = nodeId
        self.flags = flags
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.nodeId = protobuf.hasNodeID ? UUID(msgdef: protobuf.nodeID) : nil
        self.flags = GetAccessibilityTreeRequestFlags(rawValue: protobuf.flags)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        if let val = self.nodeId {
            message.nodeID = val.asMsgDef()
        }
        message.flags = flags.rawValue

        return message
    }
}

public struct GetAccessibilityTreeResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetAccessibilityTreeResponse

    public let requestId: UInt64
    public let success: Bool
    public let errorMessage: String?
    public let rootNode: AccessibilityNode?

    public init(requestId: UInt64, success: Bool, errorMessage: String?, rootNode: AccessibilityNode?) {
        self.requestId = requestId
        self.success = success
        self.errorMessage = errorMessage
        self.rootNode = rootNode
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.success = protobuf.success
        self.errorMessage = protobuf.hasErrorMessage ? protobuf.errorMessage : nil
        self.rootNode = protobuf.hasRootNode ? try AccessibilityNode(from: protobuf.rootNode) : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.success = success
        if let val = self.errorMessage {
            message.errorMessage = val
        }
        if let val = self.rootNode {
            message.rootNode = val.toProtobufMessage()
        }

        return message
    }
}

public struct SubscribeAccessibilityTreeUpdatesRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesRequest

    public let requestId: UInt64
    public let nodeId: UUID?
    public let eventMask: AccessibilityUpdateType
    public let maxDepth: UInt32
    public let flags: GetAccessibilityTreeRequestFlags

    public init(
        requestId: UInt64,
        nodeId: UUID?,
        eventMask: AccessibilityUpdateType,
        maxDepth: UInt32,
        flags: GetAccessibilityTreeRequestFlags
    ) {
        self.requestId = requestId
        self.nodeId = nodeId
        self.eventMask = eventMask
        self.maxDepth = maxDepth
        self.flags = flags
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.nodeId = protobuf.hasNodeID ? UUID(msgdef: protobuf.nodeID) : nil
        self.eventMask = AccessibilityUpdateType(rawValue: protobuf.eventMask)
        self.maxDepth = protobuf.maxDepth
        self.flags = GetAccessibilityTreeRequestFlags(rawValue: protobuf.flags)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        if let val = self.nodeId {
            message.nodeID = val.asMsgDef()
        }
        message.eventMask = eventMask.rawValue
        message.maxDepth = maxDepth
        message.flags = flags.rawValue

        return message
    }
}

public struct SubscribeAccessibilityTreeUpdatesResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_SubscribeAccessibilityTreeUpdatesResponse

    public let requestId: UInt64
    public let subscriptionId: UUID
    public let success: Bool
    public let errorMessage: String?

    public init(requestId: UInt64, subscriptionId: UUID, success: Bool, errorMessage: String?) {
        self.requestId = requestId
        self.subscriptionId = subscriptionId
        self.success = success
        self.errorMessage = errorMessage
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.subscriptionId = UUID(msgdef: protobuf.subscriptionID)
        self.success = protobuf.success
        self.errorMessage = protobuf.hasErrorMessage ? protobuf.errorMessage : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.subscriptionID = subscriptionId.asMsgDef()
        message.success = success
        if let val = self.errorMessage {
            message.errorMessage = val
        }

        return message
    }
}

public struct UnsubscribeAccessibilityTreeUpdatesRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesRequest

    public let requestId: UInt64
    public let subscriptionId: UUID

    public init(requestId: UInt64, subscriptionId: UUID) {
        self.requestId = requestId
        self.subscriptionId = subscriptionId
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.subscriptionId = UUID(msgdef: protobuf.subscriptionID)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.subscriptionID = subscriptionId.asMsgDef()

        return message
    }
}

public struct UnsubscribeAccessibilityTreeUpdatesResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_UnsubscribeAccessibilityTreeUpdatesResponse

    public let requestId: UInt64
    public let subscriptionId: UUID
    public let isSuccess: Bool

    public init(requestId: UInt64, subscriptionId: UUID, isSuccess: Bool) {
        self.requestId = requestId
        self.subscriptionId = subscriptionId
        self.isSuccess = isSuccess
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.subscriptionId = UUID(msgdef: protobuf.subscriptionID)
        self.isSuccess = protobuf.isSuccess
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.subscriptionID = subscriptionId.asMsgDef()
        message.isSuccess = isSuccess

        return message
    }
}

public struct AccessibilityTreeUpdateEvent: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_AccessibilityTreeUpdateEvent

    public let subscriptionId: UUID
    public let eventType: AccessibilityUpdateType
    public let nodeId: UUID
    public let updatedNode: AccessibilityNode?

    public init(
        subscriptionId: UUID,
        eventType: AccessibilityUpdateType,
        nodeId: UUID,
        updatedNode: AccessibilityNode?
    ) {
        self.subscriptionId = subscriptionId
        self.eventType = eventType
        self.nodeId = nodeId
        self.updatedNode = updatedNode
    }

    init(from protobuf: ProtobufMessage) throws {
        self.subscriptionId = UUID(msgdef: protobuf.subscriptionID)
        self.eventType = AccessibilityUpdateType(rawValue: protobuf.eventType)
        self.nodeId = UUID(msgdef: protobuf.nodeID)
        self.updatedNode = protobuf.hasUpdatedNode ? try AccessibilityNode(from: protobuf.updatedNode) : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.subscriptionID = subscriptionId.asMsgDef()
        message.eventType = eventType.rawValue
        message.nodeID = nodeId.asMsgDef()
        if let val = self.updatedNode {
            message.updatedNode = val.toProtobufMessage()
        }

        return message
    }
}

public struct DispatchActionRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_DispatchActionRequest

    public let requestId: UInt64
    public let targetNodeId: UUID
    public let actionType: AccessibilityActionType
    public let value: AccessibilityNodeValue?
    public let args: [String: String]

    public init(
        requestId: UInt64,
        targetNodeId: UUID,
        actionType: AccessibilityActionType,
        value: AccessibilityNodeValue?,
        args: [String: String]
    ) {
        self.requestId = requestId
        self.targetNodeId = targetNodeId
        self.actionType = actionType
        self.value = value
        self.args = args
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.targetNodeId = UUID(msgdef: protobuf.targetNodeID)
        self.actionType = AccessibilityActionType(rawValue: protobuf.actionType)
        self.value = protobuf.hasValue ? try AccessibilityNodeValue(from: protobuf.value) : nil
        self.args = protobuf.args
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.targetNodeID = targetNodeId.asMsgDef()
        message.actionType = actionType.rawValue
        if let val = self.value {
            message.value = val.toProtobufMessage()
        }
        message.args = args

        return message
    }
}

public struct DispatchActionResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_DispatchActionResponse

    public let requestId: UInt64
    public let success: Bool
    public let errorMessage: String?

    public init(requestId: UInt64, success: Bool, errorMessage: String?) {
        self.requestId = requestId
        self.success = success
        self.errorMessage = errorMessage
    }

    init(from protobuf: ProtobufMessage) throws {
        self.requestId = protobuf.requestID
        self.success = protobuf.success
        self.errorMessage = protobuf.hasErrorMessage ? protobuf.errorMessage : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = requestId
        message.success = success
        if let val = self.errorMessage {
            message.errorMessage = val
        }

        return message
    }
}
