//
//  projection_audio+Constants.swift
//  SiriusKit
//
//  Auto-generated by mdproto-gen-swift. DO NOT EDIT.
//

import Foundation

public struct AudioFourCC: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    /// Opus Audio Codec
    public static let opus = AudioFourCC(rawValue: 0x4F505553)
    /// G.711 mu-law
    public static let pcmu = AudioFourCC(rawValue: 0x50434D55)
    /// G.711 A-law
    public static let pcma = AudioFourCC(rawValue: 0x50434D41)
}

public struct AudioSessionFailureReason: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    public static let unknown = AudioSessionFailureReason(rawValue: 0)
    /// 요청한 오디오 소스를 찾을 수 없음
    public static let sourceNotFound = AudioSessionFailureReason(rawValue: 1)
    /// 지원하지 않는 오디오 코덱임
    public static let codecNotSupported = AudioSessionFailureReason(rawValue: 2)
    /// 오디오 캡쳐 권한이 거부됨
    public static let permissionDenied = AudioSessionFailureReason(rawValue: 3)
}

public struct AudioSessionChangeReason: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    public static let unknown = AudioSessionChangeReason(rawValue: 0)
    /// 오디오 소스가 변경됨
    public static let sourceChanged = AudioSessionChangeReason(rawValue: 1)
    /// 코덱 설정이 재협상됨
    public static let codecRenegotiated = AudioSessionChangeReason(rawValue: 2)
}

public struct AudioSessionEndReason: RawRepresentable, Hashable, Equatable, Codable, Sendable {
    public let rawValue: UInt32

    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }

    public static let unknown = AudioSessionEndReason(rawValue: 0)
    /// 클라이언트의 요청으로 종료됨
    public static let clientRequested = AudioSessionEndReason(rawValue: 1)
    /// 오디오 소스를 더 이상 사용할 수 없음
    public static let sourceUnavailable = AudioSessionEndReason(rawValue: 2)
    /// 오류로 인해 종료됨
    public static let error = AudioSessionEndReason(rawValue: 3)
}
