//
//  projection_source+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius. DO NOT EDIT.
//

import Foundation
internal import SwiftProtobuf


public struct EntireDisplayProjectionSource: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource
    
    public let displayID: Int32


    public init(displayID: Int32) {
        self.displayID = displayID
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource) throws {
        self.displayID = protobufMessage.displayID
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.displayID = self.displayID

        return message
    }
}

public struct DisplayRegionProjectionSource: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource
    
    public let displayID: Int32
    public let region: SRRect

    public init(displayID: Int32, region: SRRect) {
        self.displayID = displayID
        self.region = region
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource) throws {
        self.displayID = protobufMessage.displayID
        self.region = SRRect(from: protobufMessage.region)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.displayID = self.displayID
        message.region = self.region.toProtobufMessage()

        return message
    }
}

public struct SingleWindowProjectionSource: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource
    
    public let windowID: Int64?
    public let flags: SingleWindowProjectionSourceFlags


    public init(windowID: Int64?, flags: SingleWindowProjectionSourceFlags) {
        self.windowID = windowID
        self.flags = flags
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource) throws {
        self.windowID = protobufMessage.hasWindowID ? protobufMessage.windowID : nil
        self.flags = .init(rawValue: protobufMessage.flags)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        if let val = self.windowID {
            message.windowID = val
        }
        message.flags = self.flags.rawValue

        return message
    }
}

public struct ProjectionSource: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_ProjectionSource
    
    public enum OneOf_Value: Sendable {
        case entireDisplay(EntireDisplayProjectionSource)
        case region(DisplayRegionProjectionSource)
        case singleWindow(SingleWindowProjectionSource)
        case none
    }

    public let flags: ProjectionSourceFlags

    public let value: OneOf_Value

    public init(value: OneOf_Value, flags: ProjectionSourceFlags) {
        self.value = value
        self.flags = flags
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_ProjectionSource) throws {
        self.flags = ProjectionSourceFlags(rawValue: UInt32(protobufMessage.flags))
        switch protobufMessage.value {
        case .entireDisplay(let val):
            self.value = .entireDisplay(try EntireDisplayProjectionSource(from: val))
            break
        case .region(let val):
            self.value = .region(try DisplayRegionProjectionSource(from: val))
            break
        case .singleWindow(let val):
            self.value = .singleWindow(try SingleWindowProjectionSource(from: val))
            break
        case .none:
            self.value = .none
            break
        }
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.flags = self.flags.rawValue
        
        switch self.value {
        case .entireDisplay(let val):
            message.value = .entireDisplay(val.toProtobufMessage())
            break
        case .region(let val):
            message.value = .region(val.toProtobufMessage())
            break
        case .singleWindow(let val):
            message.value = .singleWindow(val.toProtobufMessage())
            break
        case .none:
            break
        }

        return message
    }
}

