//
//  hid_mouse+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius. DO NOT EDIT.
//

import Foundation
internal import SwiftProtobuf


public struct CursorPositionPixel: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Hidio_CursorPositionPixel
    
    public let x: Int32
    public let y: Int32

    public init(x: Int32, y: Int32) {
        self.x = x
        self.y = y
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Hidio_CursorPositionPixel) throws {
        self.x = protobufMessage.x
        self.y = protobufMessage.y
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.x = self.x
        message.y = self.y

        return message
    }
}

public struct CursorPositionPercent: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Hidio_CursorPositionPercent
    
    public let x: Float
    public let y: Float

    public init(x: Float, y: Float) {
        self.x = x
        self.y = y
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Hidio_CursorPositionPercent) throws {
        self.x = protobufMessage.x
        self.y = protobufMessage.y
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.x = self.x
        message.y = self.y

        return message
    }
}

public enum CursorPositionScope {
    case displayId(Int32)
    case windowId(Int64)
    
    internal static func from(_ pbMessage: Sirius_Msgdef_V1_Channels_Hidio_CursorPositionScope) throws -> Self {
        switch pbMessage.scope {
        case .displayID(let val):
            return .displayId(Int32(val))
        case .windowID(let val):
            return .windowId(Int64(val))
        case .none:
            throw SiriusMessageError.invalidProtobufMessage
        }
    }
    
    internal func toProtobufEnum() -> Sirius_Msgdef_V1_Channels_Hidio_CursorPositionScope {
        var message = Sirius_Msgdef_V1_Channels_Hidio_CursorPositionScope()
        
        switch self {
        case .displayId(let val):
            message.scope = .displayID(val)
            break
        case .windowId(let val):
            message.scope = .windowID(val)
            break
        }
        
        return message
    }
}

public struct MouseMoveEvent: HIDEvent, HIDEventConvertable {
    public enum OneOf_CursorPosition {
        case pixel(CursorPositionPixel)
        case percent(CursorPositionPercent)
    }
    
    public static let kind: HIDIOEventKind = .mouseMove
    
    public let moveType: MouseMoveEventType
    public let scope: CursorPositionScope
    
    public let position: OneOf_CursorPosition
    
    public let pressure: Int32?
    
    public init(moveType: MouseMoveEventType, scope: CursorPositionScope, position: OneOf_CursorPosition, pressure: Int32? = nil) {
        self.moveType = moveType
        self.scope = scope
        self.position = position
        self.pressure = pressure
    }
    
    static func from(_ container: Sirius_Msgdef_V1_Channels_Hidio_HIDEvent) throws -> Self {
        guard case .mouseMoveEvent(let message) = container.event else {
            throw SiriusMessageError.invalidProtobufMessage
        }
        
        let event = Self(
            moveType: .init(rawValue: message.moveType),
            scope: try CursorPositionScope.from(message.scope),
            position: try {
                switch message.position {
                case .pixel(let val):
                    return .pixel(try CursorPositionPixel(from: val))
                case .percent(let val):
                    return .percent(try CursorPositionPercent(from: val))
                case .none:
                    throw SiriusMessageError.invalidProtobufMessage
                }
            }(),
            pressure: message.hasPressure ? message.pressure : nil
        )
        
        return consume event
    }
    
    func toProtobufMessage() -> Sirius_Msgdef_V1_Channels_Hidio_HIDEvent {
        var message = Sirius_Msgdef_V1_Channels_Hidio_HIDEvent()
        
        var mouseMoveEventMessage = Sirius_Msgdef_V1_Channels_Hidio_MouseMoveEvent()
        
        mouseMoveEventMessage.moveType = self.moveType.rawValue
        mouseMoveEventMessage.scope = self.scope.toProtobufEnum()
        
        switch self.position {
        case .pixel(let val):
            mouseMoveEventMessage.position = .pixel(val.toProtobufMessage())
            break
        case .percent(let val):
            mouseMoveEventMessage.position = .percent(val.toProtobufMessage())
            break
        }
        
        if let pressure = self.pressure {
            mouseMoveEventMessage.pressure = pressure
        }
        
        
        message.event = .mouseMoveEvent(mouseMoveEventMessage)
        
        return message
    }
}

public struct MouseButtonEvent: HIDEvent, HIDEventConvertable {
    public static let kind: HIDIOEventKind = .mouseButton
    
    public let eventType: MouseButtonEventType
    public let button: MouseButtonType

    public init(eventType: MouseButtonEventType, button: MouseButtonType) {
        self.eventType = eventType
        self.button = button
    }

    static func from(_ container: Sirius_Msgdef_V1_Channels_Hidio_HIDEvent) throws -> Self {
        guard case .mouseButtonEvent(let message) = container.event else {
            throw SiriusMessageError.invalidProtobufMessage
        }
        
        let event = Self(
            eventType: .init(rawValue: message.eventType),
            button: .init(rawValue: message.button)
        )
        
        return consume event
    }

    func toProtobufMessage() -> Sirius_Msgdef_V1_Channels_Hidio_HIDEvent {
        var container = Sirius_Msgdef_V1_Channels_Hidio_HIDEvent()
        
        var message = Sirius_Msgdef_V1_Channels_Hidio_MouseButtonEvent()

        message.eventType = self.eventType.rawValue
        message.button = self.button.rawValue

        container.event = .mouseButtonEvent(message)
        
        return container
    }
}

public struct MouseWheelEvent: HIDEvent, HIDEventConvertable {
    public static let kind: HIDIOEventKind = .mouseWheel
    
    public let deltaX: Float
    public let deltaY: Float

    public init(deltaX: Float, deltaY: Float) {
        self.deltaX = deltaX
        self.deltaY = deltaY
    }

    static func from(_ container: Sirius_Msgdef_V1_Channels_Hidio_HIDEvent) throws -> Self {
        guard case .mouseWheelEvent(let message) = container.event else {
            throw SiriusMessageError.invalidProtobufMessage
        }
        
        let event = Self(
            deltaX: message.deltaX,
            deltaY: message.deltaY
        )
        
        return consume event
    }

    func toProtobufMessage() -> Sirius_Msgdef_V1_Channels_Hidio_HIDEvent {
        var container = Sirius_Msgdef_V1_Channels_Hidio_HIDEvent()
        
        var message = Sirius_Msgdef_V1_Channels_Hidio_MouseWheelEvent()

        message.deltaX = self.deltaX
        message.deltaY = self.deltaY
        
        container.event = .mouseWheelEvent(message)

        return container
    }
}

