// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/projection/displayman.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Sirius_Msgdef_V1_Channels_Projection_DisplayKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  //// 알 수 없는 디스플레이 종류.
  case unknown // = 0

  //// 내부 디스플레이 (노트북 내장 디스플레이 등)
  case `internal` // = 1

  //// 외부 디스플레이 (모니터 장비 등)
  case external // = 2

  //// 가상 디스플레이 (예: 무선 디스플레이 어댑터 등)
  case virtual // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .internal
    case 2: self = .external
    case 3: self = .virtual
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .internal: return 1
    case .external: return 2
    case .virtual: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_DisplayKind] = [
    .unknown,
    .internal,
    .external,
    .virtual,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_DisplayColorDepth: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  //// 알 수 없는 컬러 깊이
  case unknown // = 0

  //// 흑백(그레이스케일) 컬러 깊이
  case grayscale // = 1

  //// 인덱스 (팔레트가 정의된) 16색 컬러
  case indexed16Color // = 2

  //// 인덱스 (팔레트가 정의된) 256색 컬러
  case indexed256Color // = 3

  //// 8비트 컬러 (RGB8, 0~255)
  case displayColorDepth8Bit // = 4

  //// 10비트 컬러 (RGB10, 0~1023)
  case displayColorDepth10Bit // = 5
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .grayscale
    case 2: self = .indexed16Color
    case 3: self = .indexed256Color
    case 4: self = .displayColorDepth8Bit
    case 5: self = .displayColorDepth10Bit
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .grayscale: return 1
    case .indexed16Color: return 2
    case .indexed256Color: return 3
    case .displayColorDepth8Bit: return 4
    case .displayColorDepth10Bit: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_DisplayColorDepth] = [
    .unknown,
    .grayscale,
    .indexed16Color,
    .indexed256Color,
    .displayColorDepth8Bit,
    .displayColorDepth10Bit,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_DisplayDynamicRange: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  //// 표준 다이나믹 레인지 (SDR)
  case sdr // = 0

  //// 하이 다이나믹 레인지 (HDR)
  case hdr // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .sdr
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .sdr
    case 1: self = .hdr
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .sdr: return 0
    case .hdr: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_DisplayDynamicRange] = [
    .sdr,
    .hdr,
  ]

}

//// 상수 정의용. protobuf의 enum은 signed인 탓도 있으므로 이 타입을 직접 사용하지 마십시오.
enum Sirius_Msgdef_V1_Channels_Projection_DisplayChangeEventType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  //// 사용 금지
  case none // = 0

  //// 디스플레이가 연결되었습니다.
  case connected // = 1

  //// 디스플레이가 연결 해제되었습니다.
  case disconnected // = 2

  //// 디스플레이의 지오메트리 / 색상 정보 등이 변경되었습니다.
  case modified // = 4

  //// 디스플레이가 기본 디스플레이로 설정되었습니다.
  case becamePrimary // = 8
  case UNRECOGNIZED(Int)

  init() {
    self = .none
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .connected
    case 2: self = .disconnected
    case 4: self = .modified
    case 8: self = .becamePrimary
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .none: return 0
    case .connected: return 1
    case .disconnected: return 2
    case .modified: return 4
    case .becamePrimary: return 8
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_DisplayChangeEventType] = [
    .none,
    .connected,
    .disconnected,
    .modified,
    .becamePrimary,
  ]

}

//// 디스플레이 목록을 요청합니다. (request-response 모델)
/// opcode = 0x8201
struct Sirius_Msgdef_V1_Channels_Projection_DisplayListRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  /// reserved
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sirius_Msgdef_V1_Channels_Projection_DisplayState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 디스플레이가 메인 디스플레이인지 여부
  var isPrimary: Bool = false

  //// 디스플레이가 현재 연결되어 있는지 여부
  var isConnected: Bool = false

  //// 디스플레이가 현재 활성화(켜져 있음) 상태인지 여부
  var isActive: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sirius_Msgdef_V1_Channels_Projection_DisplayPhysicalSizeInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 디스플레이의 물리적 크기 (밀리미터 단위)
  var physicalSize: Sirius_Msgdef_V1_Channels_Projection_SRSize {
    get {return _physicalSize ?? Sirius_Msgdef_V1_Channels_Projection_SRSize()}
    set {_physicalSize = newValue}
  }
  /// Returns true if `physicalSize` has been explicitly set.
  var hasPhysicalSize: Bool {return self._physicalSize != nil}
  /// Clears the value of `physicalSize`. Subsequent reads from it will return its default value.
  mutating func clearPhysicalSize() {self._physicalSize = nil}

  //// 디스플레이의 픽셀 밀도 (DPI: Dots Per Inch)
  var dpi: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _physicalSize: Sirius_Msgdef_V1_Channels_Projection_SRSize? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_DisplayInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// OS / DM에서 부여한 디스플레이 식별용 ID.
  var displayID: UInt32 {
    get {return _storage._displayID}
    set {_uniqueStorage()._displayID = newValue}
  }

  //// 디스플레이 종류.
  var kind: Sirius_Msgdef_V1_Channels_Projection_DisplayKind {
    get {return _storage._kind}
    set {_uniqueStorage()._kind = newValue}
  }

  //// 디스플레이 (모니터 장비)의 표시 이름.
  //// @note 이 값은 서버 구현체에 따라 비어있을 수 있거나 표준적이지 않을 수 있습니다.
  var displayName: String {
    get {return _storage._displayName}
    set {_uniqueStorage()._displayName = newValue}
  }

  //// 디스플레이 상태 정보
  var state: Sirius_Msgdef_V1_Channels_Projection_DisplayState {
    get {return _storage._state ?? Sirius_Msgdef_V1_Channels_Projection_DisplayState()}
    set {_uniqueStorage()._state = newValue}
  }
  /// Returns true if `state` has been explicitly set.
  var hasState: Bool {return _storage._state != nil}
  /// Clears the value of `state`. Subsequent reads from it will return its default value.
  mutating func clearState() {_uniqueStorage()._state = nil}

  //// 디스플레이의 해상도 및 위치 정보
  //// @property x: 전체 가상 화면 좌표계에서의 왼쪽 위 모서리 X 좌표
  //// @property y: 전체 가상 화면 좌표계에서의 왼쪽 위 모서리 Y 좌표
  //// @property width: 디스플레이의 픽셀 단위 너비
  //// @property height: 디스플레이의 픽셀 단위 높이
  var bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect {
    get {return _storage._bounds ?? Sirius_Msgdef_V1_Channels_Projection_SRRect()}
    set {_uniqueStorage()._bounds = newValue}
  }
  /// Returns true if `bounds` has been explicitly set.
  var hasBounds: Bool {return _storage._bounds != nil}
  /// Clears the value of `bounds`. Subsequent reads from it will return its default value.
  mutating func clearBounds() {_uniqueStorage()._bounds = nil}

  //// 디스플레이의 주사율 (Hz)
  //// 59.94, 23.976 등의 값이 있을 수 있으므로 float으로 표현한다.
  ////
  //// @note 서버 구현체나 플랫폼, 디스플레이 종류에 따라 이 값이 실제 디스플레이의 어빌리티와 다르거나 제공되지 않을 수 있습니다.
  ////       (0이나, 음수, 혹은 매우 비정상적인 값이 올 수 있음)
  var refreshRate: Float {
    get {return _storage._refreshRate}
    set {_uniqueStorage()._refreshRate = newValue}
  }

  //// 디스플레이의 색상 깊이
  var colorDepth: Sirius_Msgdef_V1_Channels_Projection_DisplayColorDepth {
    get {return _storage._colorDepth}
    set {_uniqueStorage()._colorDepth = newValue}
  }

  //// 디스플레이의 다이나믹 레인지
  var dynamicRange: Sirius_Msgdef_V1_Channels_Projection_DisplayDynamicRange {
    get {return _storage._dynamicRange}
    set {_uniqueStorage()._dynamicRange = newValue}
  }

  //// 디스플레이의 색상 프로파일
  var colorProfile: String {
    get {return _storage._colorProfile ?? String()}
    set {_uniqueStorage()._colorProfile = newValue}
  }
  /// Returns true if `colorProfile` has been explicitly set.
  var hasColorProfile: Bool {return _storage._colorProfile != nil}
  /// Clears the value of `colorProfile`. Subsequent reads from it will return its default value.
  mutating func clearColorProfile() {_uniqueStorage()._colorProfile = nil}

  //// 디스플레이의 물리적 크기 정보
  //// @note 이 값이 제공되지 않는 경우가 있을 수 있습니다.
  var physicalSizeInfo: Sirius_Msgdef_V1_Channels_Projection_DisplayPhysicalSizeInfo {
    get {return _storage._physicalSizeInfo ?? Sirius_Msgdef_V1_Channels_Projection_DisplayPhysicalSizeInfo()}
    set {_uniqueStorage()._physicalSizeInfo = newValue}
  }
  /// Returns true if `physicalSizeInfo` has been explicitly set.
  var hasPhysicalSizeInfo: Bool {return _storage._physicalSizeInfo != nil}
  /// Clears the value of `physicalSizeInfo`. Subsequent reads from it will return its default value.
  mutating func clearPhysicalSizeInfo() {_uniqueStorage()._physicalSizeInfo = nil}

  //// 추가 메타데이터
  //// @note **모든 메타데이터 키는 optional입니다**. 모든 서버 구현체가 이를 반드시 지원한다는 보장은 없고, 모든 키가 항상 제공되는 것도 아닙니다.
  //// @note 구현체-specific 메타데이터 키는 reversed domain name 형식을 따르십시오. (예: "com.contoso.superremote.virtual-display-purpose" 등)
  //// @key "related-display-id": 이 디스플레이가 다른 디스플레이의 미러링을 수행하고 있는 경우, 그 원본 디스플레이 ID를 나타냅니다.
  //// @key "connection-type": 디스플레이 연결 유형 (예: "HDMI", "DisplayPort", "USB-C", "Wireless" 등)
  var metadata: Dictionary<String,String> {
    get {return _storage._metadata}
    set {_uniqueStorage()._metadata = newValue}
  }

  var flags: UInt32 {
    get {return _storage._flags}
    set {_uniqueStorage()._flags = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

//// 디스플레이 목록에 대한 응답 메시지.
/// opcode = 0x8202
struct Sirius_Msgdef_V1_Channels_Projection_DisplayListResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var displays: [Sirius_Msgdef_V1_Channels_Projection_DisplayInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 서버로부터 디스플레이 변경 이벤트를 구독합니다.
/// opcode = 0x8203
struct Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 0x0000인 경우 모든 이벤트를 구독합니다.
  var eventMask: UInt32 = 0

  /// reserved
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// SubscribeDisplayChangesRequest에 대한 응답 메시지.
/// opcode = 0x8204
struct Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_UUID {
    get {return _subscriptionID ?? Sirius_Msgdef_UUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_UUID? = nil
}

//// 서버로부터 디스플레이 변경 이벤트를 구독 해제합니다.
/// opcode = 0x8205
struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_UUID {
    get {return _subscriptionID ?? Sirius_Msgdef_UUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_UUID? = nil
}

//// UnsubscribeDisplayChangesRequest에 대한 응답 메시지.
/// opcode = 0x8206
struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_UUID {
    get {return _subscriptionID ?? Sirius_Msgdef_UUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  //// 구독 해제 성공 여부.
  var isSuccess: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_UUID? = nil
}

//// 디스플레이 변경 이벤트.
/// opcode = 0x8207
struct Sirius_Msgdef_V1_Channels_Projection_DisplayChangedEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 이벤트 유형 코드
  var eventType: UInt32 = 0

  //// 변경된 디스플레이 정보
  var display: Sirius_Msgdef_V1_Channels_Projection_DisplayInfo {
    get {return _display ?? Sirius_Msgdef_V1_Channels_Projection_DisplayInfo()}
    set {_display = newValue}
  }
  /// Returns true if `display` has been explicitly set.
  var hasDisplay: Bool {return self._display != nil}
  /// Clears the value of `display`. Subsequent reads from it will return its default value.
  mutating func clearDisplay() {self._display = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _display: Sirius_Msgdef_V1_Channels_Projection_DisplayInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.projection"

extension Sirius_Msgdef_V1_Channels_Projection_DisplayKind: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DISPLAY_KIND_UNKNOWN\0\u{1}DISPLAY_KIND_INTERNAL\0\u{1}DISPLAY_KIND_EXTERNAL\0\u{1}DISPLAY_KIND_VIRTUAL\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayColorDepth: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DISPLAY_COLOR_DEPTH_UNKNOWN\0\u{1}DISPLAY_COLOR_DEPTH_GRAYSCALE\0\u{1}DISPLAY_COLOR_DEPTH_INDEXED_16_COLOR\0\u{1}DISPLAY_COLOR_DEPTH_INDEXED_256_COLOR\0\u{1}DISPLAY_COLOR_DEPTH_8BIT\0\u{1}DISPLAY_COLOR_DEPTH_10BIT\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayDynamicRange: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DISPLAY_DYNAMIC_RANGE_SDR\0\u{1}DISPLAY_DYNAMIC_RANGE_HDR\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayChangeEventType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DISPLAY_CHANGE_EVENT_TYPE_NONE\0\u{1}DISPLAY_CHANGE_EVENT_TYPE_CONNECTED\0\u{1}DISPLAY_CHANGE_EVENT_TYPE_DISCONNECTED\0\u{2}\u{2}DISPLAY_CHANGE_EVENT_TYPE_MODIFIED\0\u{2}\u{4}DISPLAY_CHANGE_EVENT_TYPE_BECAME_PRIMARY\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayListRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayListRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{2}\u{f}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 16: try { try decoder.decodeSingularFixed32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.flags != 0 {
      try visitor.visitSingularFixed32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayListRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayListRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayState"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}isPrimary\0\u{1}isConnected\0\u{1}isActive\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isPrimary) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isConnected) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isActive) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isPrimary != false {
      try visitor.visitSingularBoolField(value: self.isPrimary, fieldNumber: 1)
    }
    if self.isConnected != false {
      try visitor.visitSingularBoolField(value: self.isConnected, fieldNumber: 2)
    }
    if self.isActive != false {
      try visitor.visitSingularBoolField(value: self.isActive, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayState, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayState) -> Bool {
    if lhs.isPrimary != rhs.isPrimary {return false}
    if lhs.isConnected != rhs.isConnected {return false}
    if lhs.isActive != rhs.isActive {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayPhysicalSizeInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayPhysicalSizeInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}physicalSize\0\u{1}dpi\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._physicalSize) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self.dpi) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._physicalSize {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.dpi != 0 {
      try visitor.visitSingularFixed32Field(value: self.dpi, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayPhysicalSizeInfo, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayPhysicalSizeInfo) -> Bool {
    if lhs._physicalSize != rhs._physicalSize {return false}
    if lhs.dpi != rhs.dpi {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}displayID\0\u{1}kind\0\u{1}displayName\0\u{1}state\0\u{1}bounds\0\u{1}refreshRate\0\u{1}colorDepth\0\u{1}dynamicRange\0\u{1}colorProfile\0\u{1}physicalSizeInfo\0\u{2}\u{5}metadata\0\u{1}flags\0")

  fileprivate class _StorageClass {
    var _displayID: UInt32 = 0
    var _kind: Sirius_Msgdef_V1_Channels_Projection_DisplayKind = .unknown
    var _displayName: String = String()
    var _state: Sirius_Msgdef_V1_Channels_Projection_DisplayState? = nil
    var _bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect? = nil
    var _refreshRate: Float = 0
    var _colorDepth: Sirius_Msgdef_V1_Channels_Projection_DisplayColorDepth = .unknown
    var _dynamicRange: Sirius_Msgdef_V1_Channels_Projection_DisplayDynamicRange = .sdr
    var _colorProfile: String? = nil
    var _physicalSizeInfo: Sirius_Msgdef_V1_Channels_Projection_DisplayPhysicalSizeInfo? = nil
    var _metadata: Dictionary<String,String> = [:]
    var _flags: UInt32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _displayID = source._displayID
      _kind = source._kind
      _displayName = source._displayName
      _state = source._state
      _bounds = source._bounds
      _refreshRate = source._refreshRate
      _colorDepth = source._colorDepth
      _dynamicRange = source._dynamicRange
      _colorProfile = source._colorProfile
      _physicalSizeInfo = source._physicalSizeInfo
      _metadata = source._metadata
      _flags = source._flags
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularFixed32Field(value: &_storage._displayID) }()
        case 2: try { try decoder.decodeSingularEnumField(value: &_storage._kind) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._displayName) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._state) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._bounds) }()
        case 6: try { try decoder.decodeSingularFloatField(value: &_storage._refreshRate) }()
        case 7: try { try decoder.decodeSingularEnumField(value: &_storage._colorDepth) }()
        case 8: try { try decoder.decodeSingularEnumField(value: &_storage._dynamicRange) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._colorProfile) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._physicalSizeInfo) }()
        case 15: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._metadata) }()
        case 16: try { try decoder.decodeSingularFixed32Field(value: &_storage._flags) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._displayID != 0 {
        try visitor.visitSingularFixed32Field(value: _storage._displayID, fieldNumber: 1)
      }
      if _storage._kind != .unknown {
        try visitor.visitSingularEnumField(value: _storage._kind, fieldNumber: 2)
      }
      if !_storage._displayName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._displayName, fieldNumber: 3)
      }
      try { if let v = _storage._state {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._bounds {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if _storage._refreshRate.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._refreshRate, fieldNumber: 6)
      }
      if _storage._colorDepth != .unknown {
        try visitor.visitSingularEnumField(value: _storage._colorDepth, fieldNumber: 7)
      }
      if _storage._dynamicRange != .sdr {
        try visitor.visitSingularEnumField(value: _storage._dynamicRange, fieldNumber: 8)
      }
      try { if let v = _storage._colorProfile {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._physicalSizeInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      if !_storage._metadata.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._metadata, fieldNumber: 15)
      }
      if _storage._flags != 0 {
        try visitor.visitSingularFixed32Field(value: _storage._flags, fieldNumber: 16)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayInfo, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._displayID != rhs_storage._displayID {return false}
        if _storage._kind != rhs_storage._kind {return false}
        if _storage._displayName != rhs_storage._displayName {return false}
        if _storage._state != rhs_storage._state {return false}
        if _storage._bounds != rhs_storage._bounds {return false}
        if _storage._refreshRate != rhs_storage._refreshRate {return false}
        if _storage._colorDepth != rhs_storage._colorDepth {return false}
        if _storage._dynamicRange != rhs_storage._dynamicRange {return false}
        if _storage._colorProfile != rhs_storage._colorProfile {return false}
        if _storage._physicalSizeInfo != rhs_storage._physicalSizeInfo {return false}
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._flags != rhs_storage._flags {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayListResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}displays\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.displays) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if !self.displays.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.displays, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayListResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayListResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.displays != rhs.displays {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeDisplayChangesRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}eventMask\0\u{2}\u{e}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self.eventMask) }()
      case 16: try { try decoder.decodeSingularFixed32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.eventMask != 0 {
      try visitor.visitSingularFixed32Field(value: self.eventMask, fieldNumber: 2)
    }
    if self.flags != 0 {
      try visitor.visitSingularFixed32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.eventMask != rhs.eventMask {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeDisplayChangesResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeDisplayChangesResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeDisplayChangesRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeDisplayChangesResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0\u{1}isSuccess\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isSuccess) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.isSuccess != false {
      try visitor.visitSingularBoolField(value: self.isSuccess, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeDisplayChangesResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.isSuccess != rhs.isSuccess {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayChangedEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayChangedEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}eventType\0\u{1}display\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed32Field(value: &self.eventType) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._display) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.eventType != 0 {
      try visitor.visitSingularFixed32Field(value: self.eventType, fieldNumber: 1)
    }
    try { if let v = self._display {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayChangedEvent, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayChangedEvent) -> Bool {
    if lhs.eventType != rhs.eventType {return false}
    if lhs._display != rhs._display {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
