// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/projection/projection_source.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// 전체 디스플레이를 프로젝션할 때 사용합니다.
struct Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 디스플레이 ID.
  //// -1로 설정하는 경우 기본 디스플레이를 의미합니다.
  //// -2로 설정하는 경우 전체 디스플레이 영역을 의미합니다.
  var displayID: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 특정 디스플레이 내의 수동 지정된 영역을 프로젝션할 때 사용합니다.
struct Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 디스플레이 ID.
  //// -1로 설정하는 경우 기본 디스플레이를 의미합니다.
  //// -2로 설정하는 경우 전체 디스플레이 영역을 의미합니다.
  var displayID: Int32 = 0

  //// 프로젝션할 사각형 영역 (픽셀 단위)
  var region: Sirius_Msgdef_V1_Channels_Projection_SRRect {
    get {return _region ?? Sirius_Msgdef_V1_Channels_Projection_SRRect()}
    set {_region = newValue}
  }
  /// Returns true if `region` has been explicitly set.
  var hasRegion: Bool {return self._region != nil}
  /// Clears the value of `region`. Subsequent reads from it will return its default value.
  mutating func clearRegion() {self._region = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _region: Sirius_Msgdef_V1_Channels_Projection_SRRect? = nil
}

//// 단일 윈도우(창)를 프로젝션할 때 사용합니다.
struct Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 프로젝션할 윈도우의 고유 ID (Handle)
  var windowID: Int64 {
    get {return _windowID ?? 0}
    set {_windowID = newValue}
  }
  /// Returns true if `windowID` has been explicitly set.
  var hasWindowID: Bool {return self._windowID != nil}
  /// Clears the value of `windowID`. Subsequent reads from it will return its default value.
  mutating func clearWindowID() {self._windowID = nil}

  //// 윈도우 프로젝션 관련 플래그
  /// @optionset: SingleWindowProjectionSourceFlags
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _windowID: Int64? = nil
}

//// 프로젝션 소스 정의 (디스플레이, 영역, 또는 단일 창 중 하나)
struct Sirius_Msgdef_V1_Channels_Projection_ProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: Sirius_Msgdef_V1_Channels_Projection_ProjectionSource.OneOf_Value? = nil

  var entireDisplay: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource {
    get {
      if case .entireDisplay(let v)? = value {return v}
      return Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource()
    }
    set {value = .entireDisplay(newValue)}
  }

  var region: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource {
    get {
      if case .region(let v)? = value {return v}
      return Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource()
    }
    set {value = .region(newValue)}
  }

  var singleWindow: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource {
    get {
      if case .singleWindow(let v)? = value {return v}
      return Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource()
    }
    set {value = .singleWindow(newValue)}
  }

  //// 프로젝션 소스 공통 플래그
  /// @optionset: ProjectionSourceFlags
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Value: Equatable, Sendable {
    case entireDisplay(Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource)
    case region(Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource)
    case singleWindow(Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.projection"

extension Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EntireDisplayProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}displayId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.displayID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.displayID != 0 {
      try visitor.visitSingularSInt32Field(value: self.displayID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayRegionProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}displayId\0\u{1}region\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.displayID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._region) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.displayID != 0 {
      try visitor.visitSingularSInt32Field(value: self.displayID, fieldNumber: 1)
    }
    try { if let v = self._region {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs._region != rhs._region {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SingleWindowProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}windowId\0\u{2}\u{f}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSInt64Field(value: &self._windowID) }()
      case 16: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._windowID {
      try visitor.visitSingularSInt64Field(value: v, fieldNumber: 1)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource) -> Bool {
    if lhs._windowID != rhs._windowID {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_ProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entireDisplay\0\u{1}region\0\u{1}singleWindow\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .entireDisplay(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .entireDisplay(v)
        }
      }()
      case 2: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .region(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .region(v)
        }
      }()
      case 3: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .singleWindow(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .singleWindow(v)
        }
      }()
      case 16: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .entireDisplay?: try {
      guard case .entireDisplay(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .region?: try {
      guard case .region(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .singleWindow?: try {
      guard case .singleWindow(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_ProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_ProjectionSource) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
