// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/projection/projection_source.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSourceFlags: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case singleWindowProjectionFlagNone // = 0
  case singleWindowProjectionFlagFollowSource // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .singleWindowProjectionFlagNone
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .singleWindowProjectionFlagNone
    case 1: self = .singleWindowProjectionFlagFollowSource
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .singleWindowProjectionFlagNone: return 0
    case .singleWindowProjectionFlagFollowSource: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSourceFlags] = [
    .singleWindowProjectionFlagNone,
    .singleWindowProjectionFlagFollowSource,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_ProjectionSourceFlags: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case displayViewportFlagNone // = 0
  case UNRECOGNIZED(Int)

  init() {
    self = .displayViewportFlagNone
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .displayViewportFlagNone
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .displayViewportFlagNone: return 0
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_ProjectionSourceFlags] = [
    .displayViewportFlagNone,
  ]

}

//// 전체 디스플레이를 프로젝션할 때 사용합니다.
struct Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var displayID: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 수동으로 직접 프로젝션할 뷰포트를 지정합니다.
struct Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 디스플레이 ID.
  //// -1로 설정하는 경우 기본 디스플레이를 의미합니다.
  //// -2로 설정하는 경우 전체 디스플레이 영역을 의미합니다.
  var displayID: Int32 = 0

  //// 왼쪽 위 모서리의 X 좌표
  var x: UInt32 = 0

  //// 왼쪽 위 모서리의 Y 좌표
  var y: UInt32 = 0

  //// 너비
  var width: UInt32 = 0

  //// 높이
  var height: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// 단일 창을 프로젝션할 때 사용합니다.
struct Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// TODO: Add more window identification methods (e.g., by process ID, by window title, etc.)
  var windowID: Int64 {
    get {return _windowID ?? 0}
    set {_windowID = newValue}
  }
  /// Returns true if `windowID` has been explicitly set.
  var hasWindowID: Bool {return self._windowID != nil}
  /// Clears the value of `windowID`. Subsequent reads from it will return its default value.
  mutating func clearWindowID() {self._windowID = nil}

  var flags: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSourceFlags = .singleWindowProjectionFlagNone

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _windowID: Int64? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_ProjectionSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: Sirius_Msgdef_V1_Channels_Projection_ProjectionSource.OneOf_Value? = nil

  var entireDisplay: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource {
    get {
      if case .entireDisplay(let v)? = value {return v}
      return Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource()
    }
    set {value = .entireDisplay(newValue)}
  }

  var region: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource {
    get {
      if case .region(let v)? = value {return v}
      return Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource()
    }
    set {value = .region(newValue)}
  }

  var singleWindow: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource {
    get {
      if case .singleWindow(let v)? = value {return v}
      return Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource()
    }
    set {value = .singleWindow(newValue)}
  }

  var flags: Sirius_Msgdef_V1_Channels_Projection_ProjectionSourceFlags = .displayViewportFlagNone

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Value: Equatable, Sendable {
    case entireDisplay(Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource)
    case region(Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource)
    case singleWindow(Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.projection"

extension Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSourceFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SINGLE_WINDOW_PROJECTION_FLAG_NONE\0\u{1}SINGLE_WINDOW_PROJECTION_FLAG_FOLLOW_SOURCE\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_ProjectionSourceFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DISPLAY_VIEWPORT_FLAG_NONE\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EntireDisplayProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}displayId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSFixed32Field(value: &self.displayID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.displayID != 0 {
      try visitor.visitSingularSFixed32Field(value: self.displayID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DisplayRegionProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}displayId\0\u{1}x\0\u{1}y\0\u{1}width\0\u{1}height\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSFixed32Field(value: &self.displayID) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self.x) }()
      case 3: try { try decoder.decodeSingularFixed32Field(value: &self.y) }()
      case 4: try { try decoder.decodeSingularFixed32Field(value: &self.width) }()
      case 5: try { try decoder.decodeSingularFixed32Field(value: &self.height) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.displayID != 0 {
      try visitor.visitSingularSFixed32Field(value: self.displayID, fieldNumber: 1)
    }
    if self.x != 0 {
      try visitor.visitSingularFixed32Field(value: self.x, fieldNumber: 2)
    }
    if self.y != 0 {
      try visitor.visitSingularFixed32Field(value: self.y, fieldNumber: 3)
    }
    if self.width != 0 {
      try visitor.visitSingularFixed32Field(value: self.width, fieldNumber: 4)
    }
    if self.height != 0 {
      try visitor.visitSingularFixed32Field(value: self.height, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SingleWindowProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}windowId\0\u{2}\u{f}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSFixed64Field(value: &self._windowID) }()
      case 16: try { try decoder.decodeSingularEnumField(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._windowID {
      try visitor.visitSingularSFixed64Field(value: v, fieldNumber: 1)
    } }()
    if self.flags != .singleWindowProjectionFlagNone {
      try visitor.visitSingularEnumField(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource) -> Bool {
    if lhs._windowID != rhs._windowID {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_ProjectionSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProjectionSource"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entireDisplay\0\u{1}region\0\u{1}singleWindow\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_EntireDisplayProjectionSource?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .entireDisplay(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .entireDisplay(v)
        }
      }()
      case 2: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_DisplayRegionProjectionSource?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .region(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .region(v)
        }
      }()
      case 3: try {
        var v: Sirius_Msgdef_V1_Channels_Projection_SingleWindowProjectionSource?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .singleWindow(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .singleWindow(v)
        }
      }()
      case 16: try { try decoder.decodeSingularEnumField(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .entireDisplay?: try {
      guard case .entireDisplay(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .region?: try {
      guard case .region(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .singleWindow?: try {
      guard case .singleWindow(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    if self.flags != .displayViewportFlagNone {
      try visitor.visitSingularEnumField(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_ProjectionSource, rhs: Sirius_Msgdef_V1_Channels_Projection_ProjectionSource) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
