// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/projection/winman_query.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// 상수 정의용. protobuf의 enum은 signed인 탓도 있으므로 이 타입을 직접 사용하지 마십시오.
enum Sirius_Msgdef_V1_Channels_Projection_WindowInfoFlags: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case windowInfoFlagNone // = 0

  //// 윈도우가 현재 포커스를 받고 있습니다.
  case windowInfoFlagIsFocused // = 1

  //// 이 윈도우는 사용자에게 보이지 않도록 설정되어 있습니다.
  case windowInfoFlagIsHidden // = 2

  //// 이 윈도우는 타이틀 바 등의 윈도우 데코레이션을 가지고 있지 않습니다.
  case windowInfoFlagNoWindowDecoration // = 4

  //// 이 윈도우는 작업 표시줄 (Windows, Linux) 또는 독 (macOS)에 표시되지 않습니다.
  case kipWindowEntry // = 8

  //// 윈도우가 최소화 된 상태입니다.
  case windowInfoFlagIsMinimized // = 16

  //// 윈도우가 최대화 된 상태입니다.
  case windowInfoFlagIsMaximized // = 32

  //// 윈도우가 전체 화면 모드로 표시되고 있습니다.
  case windowInfoFlagIsFullscreen // = 64

  //// 이 윈도우는 최소화가 불가능합니다.
  case windowInfoFlagCannotMinimize // = 256

  //// 이 윈도우는 최대화가 불가능합니다.
  case windowInfoFlagCannotMaximize // = 512

  //// 이 윈도우는 전체 화면 모드로 전환할 수 없습니다.
  case windowInfoFlagCannotFullscreen // = 1024

  //// 이 윈도우는 항상 위에 표시되는(topmost) 상태입니다.
  case windowInfoFlagIsTopmost // = 4096

  //// 이 윈도우는 항상 아래에 표시되는(bottommost) 상태입니다.
  case windowInfoFlagIsBottommost // = 8192

  //// Linux: 이 윈도우는 컴포지터를 스킵합니다.
  //// Windows: 이 윈도우는 DWM (Desktop Window Manager)을 스킵합니다. (Aero Glass 효과 등이 적용되지 않음)
  //// - 알려진 호환성 문제가 있는 애플리케이션이나, low-latency를 보장받아야 하는 애플리케이션에 설정되어 있을 수 있습니다.
  case kipCompositor // = 65536
  case UNRECOGNIZED(Int)

  init() {
    self = .windowInfoFlagNone
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .windowInfoFlagNone
    case 1: self = .windowInfoFlagIsFocused
    case 2: self = .windowInfoFlagIsHidden
    case 4: self = .windowInfoFlagNoWindowDecoration
    case 8: self = .kipWindowEntry
    case 16: self = .windowInfoFlagIsMinimized
    case 32: self = .windowInfoFlagIsMaximized
    case 64: self = .windowInfoFlagIsFullscreen
    case 256: self = .windowInfoFlagCannotMinimize
    case 512: self = .windowInfoFlagCannotMaximize
    case 1024: self = .windowInfoFlagCannotFullscreen
    case 4096: self = .windowInfoFlagIsTopmost
    case 8192: self = .windowInfoFlagIsBottommost
    case 65536: self = .kipCompositor
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .windowInfoFlagNone: return 0
    case .windowInfoFlagIsFocused: return 1
    case .windowInfoFlagIsHidden: return 2
    case .windowInfoFlagNoWindowDecoration: return 4
    case .kipWindowEntry: return 8
    case .windowInfoFlagIsMinimized: return 16
    case .windowInfoFlagIsMaximized: return 32
    case .windowInfoFlagIsFullscreen: return 64
    case .windowInfoFlagCannotMinimize: return 256
    case .windowInfoFlagCannotMaximize: return 512
    case .windowInfoFlagCannotFullscreen: return 1024
    case .windowInfoFlagIsTopmost: return 4096
    case .windowInfoFlagIsBottommost: return 8192
    case .kipCompositor: return 65536
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowInfoFlags] = [
    .windowInfoFlagNone,
    .windowInfoFlagIsFocused,
    .windowInfoFlagIsHidden,
    .windowInfoFlagNoWindowDecoration,
    .kipWindowEntry,
    .windowInfoFlagIsMinimized,
    .windowInfoFlagIsMaximized,
    .windowInfoFlagIsFullscreen,
    .windowInfoFlagCannotMinimize,
    .windowInfoFlagCannotMaximize,
    .windowInfoFlagCannotFullscreen,
    .windowInfoFlagIsTopmost,
    .windowInfoFlagIsBottommost,
    .kipCompositor,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_WindowRole: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unknown // = 0

  //// 일반 윈도우
  case normal // = 1

  //// 다이얼로그 윈도우
  case dialog // = 2

  //// 툴팁 윈도우
  case tooltip // = 3

  //// 메뉴
  case menu // = 4

  //// 알림 윈도우
  case notification // = 5
  case UNRECOGNIZED(Int)

  init() {
    self = .unknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .normal
    case 2: self = .dialog
    case 3: self = .tooltip
    case 4: self = .menu
    case 5: self = .notification
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .normal: return 1
    case .dialog: return 2
    case .tooltip: return 3
    case .menu: return 4
    case .notification: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowRole] = [
    .unknown,
    .normal,
    .dialog,
    .tooltip,
    .menu,
    .notification,
  ]

}

//// # Window Hints
//// - 효율적인 프로젝션을 위해 윈도우에 대한 힌트를 제공할 수 있습니다.
enum Sirius_Msgdef_V1_Channels_Projection_WindowHint: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case none // = 0

  //// 이 윈도우는 시스템 UI의 일부입니다.
  //// 예시: 탐색 막대, 상태 표시줄, 알림 센터, IME 패널 (한글-한자 변환 / 일본어・중국어 변환 후보 등)
  case systemUi // = 1

  //// 이 윈도우는 시스템에 의해 응답하지 않는 것으로 보고되었습니다.
  case notResponding // = 2

  //// 이 윈도우는 시스템 정책에 의해 조작이 불가능할 것으로 예상됩니다. (다른 유저 세션의 윈도우, 고권한 프로세스의 윈도우, UAC 등)
  case inaccessible // = 4

  //// 이 윈도우는 시스템 정책에 의해 캡처가 불가능할 것으로 예상됩니다. (DRM 보호 컨텐츠 등)
  //// @note 이 힌트는 무조건 캡처가 불가능하다는 보장이 아닙니다. 실제로 캡처는 이루어질 수 있으나, 검은 화면 등으로 나타날 수 있습니다.
  case protectedContent // = 8

  //// 이 윈도우는 제 3자의 외부 DRM 솔루션, 안티-치트 솔루션 등에 의해 강력히 보호되는 것으로 보입니다.
  //// - 이 윈도우를 캡쳐하거나 원격으로 조작하려고 시도할 경우, 서버 구현체의 프로세스가 충돌하거나 강제 종료될 수도 있기 때문에 프로젝션을 권장하지 않습니다.
  //// - e.g.) AhnLab Safe Transaction, Fasoo DRM 등
  case aggressiveProtectedContent // = 16

  //// 이 윈도우는 현재 다른 창에 가려져 있거나 해서 화면에 보이지 않는 상태입니다.
  case notVisibleOnScreen // = 32

  //// 이 윈도우는 자주 변경되지 않는 정적 콘텐츠를 포함하고 있습니다.
  case staticContent // = 256

  //// 이 윈도우는 빠르게 갱신되는 동적 컨텐츠 (예: 비디오 플레이어, 게임 등)를 포함하고 있습니다.
  case dynamicContent // = 512

  //// 이 윈도우는 그림자를 포함하고 있습니다.
  //// - 윈도우 외곽에 그림자가 있는 경우에 유용합니다.
  //// - AppStream (가칭) 같은 기능을 구현할 때, 클라이언트 측에서 대신 shadow를 그리도록 할 수 있습니다.
  case hasShadow // = 4096

  //// 이 윈도우는 투명한 영역을 포함하고 있습니다.
  //// - border-radius가 설정되었거나, 부분적으로 투명한 UI를 포함하는 윈도우에 유용합니다.
  case hasTransparency // = 8192
  case UNRECOGNIZED(Int)

  init() {
    self = .none
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .systemUi
    case 2: self = .notResponding
    case 4: self = .inaccessible
    case 8: self = .protectedContent
    case 16: self = .aggressiveProtectedContent
    case 32: self = .notVisibleOnScreen
    case 256: self = .staticContent
    case 512: self = .dynamicContent
    case 4096: self = .hasShadow
    case 8192: self = .hasTransparency
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .none: return 0
    case .systemUi: return 1
    case .notResponding: return 2
    case .inaccessible: return 4
    case .protectedContent: return 8
    case .aggressiveProtectedContent: return 16
    case .notVisibleOnScreen: return 32
    case .staticContent: return 256
    case .dynamicContent: return 512
    case .hasShadow: return 4096
    case .hasTransparency: return 8192
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowHint] = [
    .none,
    .systemUi,
    .notResponding,
    .inaccessible,
    .protectedContent,
    .aggressiveProtectedContent,
    .notVisibleOnScreen,
    .staticContent,
    .dynamicContent,
    .hasShadow,
    .hasTransparency,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpressionOperator: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case matchExact // = 0
  case matchContains // = 1
  case matchIcontains // = 2

  //// ## ABOUT REGEX
  //// - REGEX 구현체는 Perl-compatible한 정규 표현식 (PCRE)를 사용하는 것을 권장하나, 강제 사항은 아닙니다.
  case matchRegex // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .matchExact
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .matchExact
    case 1: self = .matchContains
    case 2: self = .matchIcontains
    case 3: self = .matchRegex
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .matchExact: return 0
    case .matchContains: return 1
    case .matchIcontains: return 2
    case .matchRegex: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpressionOperator] = [
    .matchExact,
    .matchContains,
    .matchIcontains,
    .matchRegex,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_WindowFilterOperator: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// 모든 조건 만족
  case and // = 0

  /// 하나라도 만족
  case or // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .and
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .and
    case 1: self = .or
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .and: return 0
    case .or: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowFilterOperator] = [
    .and,
    .or,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_WindowListRequestFlags: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case windowListRequestFlagNone // = 0

  //// 페이지네이션 된 결과를 요청합니다.
  //// (사실 말이 페이지네이션이지 N개씩 분할해서 보내달라는 뜻입니다)
  //// - 페이지네이션 사이즈는 서버 구현체에 따라 다를 수 있습니다.
  case windowListRequestFlagPaginated // = 1

  //// 통상적으로 숨겨진 윈도우들도 함께 요청합니다.
  case windowListRequestFlagIncludeHiddenWindows // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .windowListRequestFlagNone
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .windowListRequestFlagNone
    case 1: self = .windowListRequestFlagPaginated
    case 2: self = .windowListRequestFlagIncludeHiddenWindows
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .windowListRequestFlagNone: return 0
    case .windowListRequestFlagPaginated: return 1
    case .windowListRequestFlagIncludeHiddenWindows: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowListRequestFlags] = [
    .windowListRequestFlagNone,
    .windowListRequestFlagPaginated,
    .windowListRequestFlagIncludeHiddenWindows,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_WindowChangeEventType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  //// 사용 금지
  case none // = 0

  //// 윈도우가 포커스를 얻었습니다.
  case focused // = 1

  //// 윈도우가 포커스를 잃었습니다.
  case unfocused // = 2

  //// 윈도우가 이동되었습니다.
  case moved // = 4

  //// 윈도우가 크기 조절되었습니다.
  case resized // = 8

  //// 윈도우가 닫혔습니다.
  case closed // = 16

  //// 윈도우의 메타데이터가 크게 변경되었습니다.
  case metadataChanged // = 32
  case UNRECOGNIZED(Int)

  init() {
    self = .none
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .focused
    case 2: self = .unfocused
    case 4: self = .moved
    case 8: self = .resized
    case 16: self = .closed
    case 32: self = .metadataChanged
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .none: return 0
    case .focused: return 1
    case .unfocused: return 2
    case .moved: return 4
    case .resized: return 8
    case .closed: return 16
    case .metadataChanged: return 32
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowChangeEventType] = [
    .none,
    .focused,
    .unfocused,
    .moved,
    .resized,
    .closed,
    .metadataChanged,
  ]

}

enum Sirius_Msgdef_V1_Channels_Projection_WindowEventSubscriptionFlags: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case windowEventSubscriptionFlagNone // = 0

  //// 구독된 윈도우 이벤트에 대한 초기 상태 스냅샷을 즉시 전송합니다.
  case endInitialSnapshot // = 1

  //// 최소한의 데이터만 포함하도록 노력합니다.
  //// - WINDOW_CHANGE_EVENT_TYPE_METADATA_CHANGED를 제외한 모든 이벤트에서, 관련 없는 WindowInfo의 필드를 생략하거나 아예 포함하지 않도록 합니다.
  //// - 이 플래그가 설정되지 않으면, 모든 이벤트에서 리치한 WindowInfo 데이터가 포함됩니다.
  case windowEventSubscriptionFlagMinimalData // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .windowEventSubscriptionFlagNone
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .windowEventSubscriptionFlagNone
    case 1: self = .endInitialSnapshot
    case 2: self = .windowEventSubscriptionFlagMinimalData
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .windowEventSubscriptionFlagNone: return 0
    case .endInitialSnapshot: return 1
    case .windowEventSubscriptionFlagMinimalData: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Sirius_Msgdef_V1_Channels_Projection_WindowEventSubscriptionFlags] = [
    .windowEventSubscriptionFlagNone,
    .endInitialSnapshot,
    .windowEventSubscriptionFlagMinimalData,
  ]

}

struct Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var `operator`: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpressionOperator = .matchExact

  var invert: Bool = false

  var field: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression.OneOf_Field? = nil

  //// 윈도우 핸들 ID로 매칭합니다.
  //// @note OS / DM에 따라 윈도우 핸들 ID의 크기가 다를 수 있으므로 fixed64 타입을 사용합니다.
  var windowID: UInt64 {
    get {
      if case .windowID(let v)? = field {return v}
      return 0
    }
    set {field = .windowID(newValue)}
  }

  //// 프로세스 ID로 매칭합니다.
  var pid: UInt64 {
    get {
      if case .pid(let v)? = field {return v}
      return 0
    }
    set {field = .pid(newValue)}
  }

  //// 윈도우 타이틀로 매칭합니다.
  var windowTitle: String {
    get {
      if case .windowTitle(let v)? = field {return v}
      return String()
    }
    set {field = .windowTitle(newValue)}
  }

  //// 애플리케이션 이름(실행 파일 이름)으로 매칭합니다.
  //// ## NOTE: Platform Differences
  //// - Windows의 경우 실행 파일 이름 (예: "chrome.exe")을 의미합니다.
  //// - macOS / Linux의 경우 프로세스 이름 (ARGV[0])을 의미합니다. 이는 전체 경로일 수도 있고, 단순 실행 파일 이름일 수도 있습니다.
  ////   - eg: `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`
  ////   - eg: `/usr/bin/google-chrome-stable`
  ////   - eg: `nginx: worker process` (자기 자신의 ARGV[0]을 수정하는 케이스)
  ////   - eg: `python3 script.py` (전체 경로가 아닌 실행 파일만 나타나는 케이스)
  var applicationName: String {
    get {
      if case .applicationName(let v)? = field {return v}
      return String()
    }
    set {field = .applicationName(newValue)}
  }

  //// 번들 ID로 매칭합니다.
  //// - 의미는 서버 구현체에 따라 다를 수 있습니다.
  ////   Noctiluca의 경우 macOS의 번들 ID (예: "com.apple.Safari")를 의미합니다.
  //// - eg) Android의 경우 패키지 이름 (예: "com.google.android.youtube")을 의미할 수 있습니다.
  var applicationBundleID: String {
    get {
      if case .applicationBundleID(let v)? = field {return v}
      return String()
    }
    set {field = .applicationBundleID(newValue)}
  }

  //// 윈도우 클래스 이름으로 매칭합니다.
  //// - macOS는 클래스 이름을 지원하지 않으므로 이 필드는 무시될 수 있습니다.
  var windowClass: String {
    get {
      if case .windowClass(let v)? = field {return v}
      return String()
    }
    set {field = .windowClass(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Field: Equatable, Sendable {
    //// 윈도우 핸들 ID로 매칭합니다.
    //// @note OS / DM에 따라 윈도우 핸들 ID의 크기가 다를 수 있으므로 fixed64 타입을 사용합니다.
    case windowID(UInt64)
    //// 프로세스 ID로 매칭합니다.
    case pid(UInt64)
    //// 윈도우 타이틀로 매칭합니다.
    case windowTitle(String)
    //// 애플리케이션 이름(실행 파일 이름)으로 매칭합니다.
    //// ## NOTE: Platform Differences
    //// - Windows의 경우 실행 파일 이름 (예: "chrome.exe")을 의미합니다.
    //// - macOS / Linux의 경우 프로세스 이름 (ARGV[0])을 의미합니다. 이는 전체 경로일 수도 있고, 단순 실행 파일 이름일 수도 있습니다.
    ////   - eg: `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`
    ////   - eg: `/usr/bin/google-chrome-stable`
    ////   - eg: `nginx: worker process` (자기 자신의 ARGV[0]을 수정하는 케이스)
    ////   - eg: `python3 script.py` (전체 경로가 아닌 실행 파일만 나타나는 케이스)
    case applicationName(String)
    //// 번들 ID로 매칭합니다.
    //// - 의미는 서버 구현체에 따라 다를 수 있습니다.
    ////   Noctiluca의 경우 macOS의 번들 ID (예: "com.apple.Safari")를 의미합니다.
    //// - eg) Android의 경우 패키지 이름 (예: "com.google.android.youtube")을 의미할 수 있습니다.
    case applicationBundleID(String)
    //// 윈도우 클래스 이름으로 매칭합니다.
    //// - macOS는 클래스 이름을 지원하지 않으므로 이 필드는 무시될 수 있습니다.
    case windowClass(String)

  }

  init() {}
}

struct Sirius_Msgdef_V1_Channels_Projection_WindowFilter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var `operator`: Sirius_Msgdef_V1_Channels_Projection_WindowFilterOperator = .and

  /// 조건들의 목록 (Recursive)
  /// 예: (A OR B) AND C 를 표현 가능
  var expressions: [Sirius_Msgdef_V1_Channels_Projection_WindowFilter] = []

  /// 혹은 단일 조건 (Leaf Node)
  var expression: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression {
    get {return _expression ?? Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression()}
    set {_expression = newValue}
  }
  /// Returns true if `expression` has been explicitly set.
  var hasExpression: Bool {return self._expression != nil}
  /// Clears the value of `expression`. Subsequent reads from it will return its default value.
  mutating func clearExpression() {self._expression = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _expression: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression? = nil
}

/// opcode = 0x8101
struct Sirius_Msgdef_V1_Channels_Projection_WindowListRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 필터 조건
  var filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter {
    get {return _filter ?? Sirius_Msgdef_V1_Channels_Projection_WindowFilter()}
    set {_filter = newValue}
  }
  /// Returns true if `filter` has been explicitly set.
  var hasFilter: Bool {return self._filter != nil}
  /// Clears the value of `filter`. Subsequent reads from it will return its default value.
  mutating func clearFilter() {self._filter = nil}

  //// 윈도우 목록 요청 플래그 (WindowListRequestFlags 참조)
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_WindowInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var windowID: UInt64 = 0

  var pid: UInt64 = 0

  var windowTitle: String = String()

  var applicationName: String = String()

  var applicationBundleID: String = String()

  var windowClass: String = String()

  var role: Sirius_Msgdef_V1_Channels_Projection_WindowRole = .unknown

  var bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect {
    get {return _bounds ?? Sirius_Msgdef_V1_Channels_Projection_SRRect()}
    set {_bounds = newValue}
  }
  /// Returns true if `bounds` has been explicitly set.
  var hasBounds: Bool {return self._bounds != nil}
  /// Clears the value of `bounds`. Subsequent reads from it will return its default value.
  mutating func clearBounds() {self._bounds = nil}

  //// 이 윈도우의 아이콘 해시값.
  var iconHash: UInt64 {
    get {return _iconHash ?? 0}
    set {_iconHash = newValue}
  }
  /// Returns true if `iconHash` has been explicitly set.
  var hasIconHash: Bool {return self._iconHash != nil}
  /// Clears the value of `iconHash`. Subsequent reads from it will return its default value.
  mutating func clearIconHash() {self._iconHash = nil}

  //// 이 윈도우의 섬네일 이미지 (PNG8 (with alpha channel) 형식, aspect ratio 유지, 최대 512x512)
  var thumbnail: Data {
    get {return _thumbnail ?? Data()}
    set {_thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  var hasThumbnail: Bool {return self._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  mutating func clearThumbnail() {self._thumbnail = nil}

  //// 추가 메타데이터
  //// @note **모든 메타데이터 키는 optional입니다**. 모든 서버 구현체가 이를 반드시 지원한다는 보장은 없고, 모든 키가 항상 제공되는 것도 아닙니다.
  //// @note 구현체-specific 메타데이터 키는 reversed domain name 형식을 따르십시오. (예: "com.contoso.superremote.virtual-display-purpose" 등)
  //// @key "related-display-id": 이 디스플레이가 다른 디스플레이의 미러링을 수행하고 있는 경우, 그 원본 디스플레이 ID를 나타냅니다.
  //// @key "connection-type": 디스플레이 연결 유형 (예: "HDMI", "DisplayPort", "USB-C", "Wireless" 등)
  var metadata: Dictionary<String,String> = [:]

  //// 윈도우 힌트 (WindowHint 참조)
  var hints: UInt32 = 0

  //// 윈도우 상태 플래그 (WindowInfoFlags 참조)
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _bounds: Sirius_Msgdef_V1_Channels_Projection_SRRect? = nil
  fileprivate var _iconHash: UInt64? = nil
  fileprivate var _thumbnail: Data? = nil
}

/// opcode = 0x8042
struct Sirius_Msgdef_V1_Channels_Projection_WindowListResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windows: [Sirius_Msgdef_V1_Channels_Projection_WindowInfo] = []

  //// 페이지네이션 된 결과의 마지막 페이지인지 여부
  var isLastPage: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// @message
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// @message
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 {
    get {return _storage._requestID}
    set {_uniqueStorage()._requestID = newValue}
  }

  var info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo {
    get {return _storage._info ?? Sirius_Msgdef_V1_Channels_Projection_WindowInfo()}
    set {_uniqueStorage()._info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  var hasInfo: Bool {return _storage._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  mutating func clearInfo() {_uniqueStorage()._info = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// @message
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// @message
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  //// 이 윈도우의 아이콘 이미지 (PNG8 (with alpha channel) 형식, requires square aspect ratio, 최대 256x256)
  var icon: Data {
    get {return _icon ?? Data()}
    set {_icon = newValue}
  }
  /// Returns true if `icon` has been explicitly set.
  var hasIcon: Bool {return self._icon != nil}
  /// Clears the value of `icon`. Subsequent reads from it will return its default value.
  mutating func clearIcon() {self._icon = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _icon: Data? = nil
}

/// @message
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// @message
struct Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var windowID: UInt64 = 0

  //// 이 윈도우의 섬네일 이미지 (PNG8 (with alpha channel) 형식, aspect ratio 유지, 최대 512x512)
  var thumbnail: Data {
    get {return _thumbnail ?? Data()}
    set {_thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  var hasThumbnail: Bool {return self._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  mutating func clearThumbnail() {self._thumbnail = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _thumbnail: Data? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 0x0000인 경우 모든 이벤트를 구독합니다.
  var eventMask: UInt32 = 0

  //// 비어있는 경우 모든 윈도우에 대한 이벤트를 구독합니다.
  var filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter {
    get {return _filter ?? Sirius_Msgdef_V1_Channels_Projection_WindowFilter()}
    set {_filter = newValue}
  }
  /// Returns true if `filter` has been explicitly set.
  var hasFilter: Bool {return self._filter != nil}
  /// Clears the value of `filter`. Subsequent reads from it will return its default value.
  mutating func clearFilter() {self._filter = nil}

  /// reserved
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _filter: Sirius_Msgdef_V1_Channels_Projection_WindowFilter? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_UUID {
    get {return _subscriptionID ?? Sirius_Msgdef_UUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_UUID? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_UUID {
    get {return _subscriptionID ?? Sirius_Msgdef_UUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_UUID? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// 구독 식별자.
  var subscriptionID: Sirius_Msgdef_UUID {
    get {return _subscriptionID ?? Sirius_Msgdef_UUID()}
    set {_subscriptionID = newValue}
  }
  /// Returns true if `subscriptionID` has been explicitly set.
  var hasSubscriptionID: Bool {return self._subscriptionID != nil}
  /// Clears the value of `subscriptionID`. Subsequent reads from it will return its default value.
  mutating func clearSubscriptionID() {self._subscriptionID = nil}

  //// 구독 해제 성공 여부.
  var isSuccess: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _subscriptionID: Sirius_Msgdef_UUID? = nil
}

struct Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// 이벤트 유형 코드 (WindowChangeEventType 참조)
  var eventType: UInt32 {
    get {return _storage._eventType}
    set {_uniqueStorage()._eventType = newValue}
  }

  var windowID: UInt64 {
    get {return _storage._windowID}
    set {_uniqueStorage()._windowID = newValue}
  }

  //// 변경된 윈도우 정보
  var info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo {
    get {return _storage._info ?? Sirius_Msgdef_V1_Channels_Projection_WindowInfo()}
    set {_uniqueStorage()._info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  var hasInfo: Bool {return _storage._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  mutating func clearInfo() {_uniqueStorage()._info = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.projection"

extension Sirius_Msgdef_V1_Channels_Projection_WindowInfoFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WINDOW_INFO_FLAG_NONE\0\u{1}WINDOW_INFO_FLAG_IS_FOCUSED\0\u{1}WINDOW_INFO_FLAG_IS_HIDDEN\0\u{2}\u{2}WINDOW_INFO_FLAG_NO_WINDOW_DECORATION\0\u{2}\u{4}WINDOW_INFO_FLAG_SKIP_WINDOW_ENTRY\0\u{2}\u{8}WINDOW_INFO_FLAG_IS_MINIMIZED\0\u{2}\u{10}WINDOW_INFO_FLAG_IS_MAXIMIZED\0\u{2} WINDOW_INFO_FLAG_IS_FULLSCREEN\0\u{2}@\u{3}WINDOW_INFO_FLAG_CANNOT_MINIMIZE\0\u{2}@\u{4}WINDOW_INFO_FLAG_CANNOT_MAXIMIZE\0\u{2}@\u{8}WINDOW_INFO_FLAG_CANNOT_FULLSCREEN\0\u{2}@0WINDOW_INFO_FLAG_IS_TOPMOST\0\u{2}@@\u{1}WINDOW_INFO_FLAG_IS_BOTTOMMOST\0\u{2}@@\u{e}WINDOW_INFO_FLAG_SKIP_COMPOSITOR\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowRole: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WINDOW_ROLE_UNKNOWN\0\u{1}WINDOW_ROLE_NORMAL\0\u{1}WINDOW_ROLE_DIALOG\0\u{1}WINDOW_ROLE_TOOLTIP\0\u{1}WINDOW_ROLE_MENU\0\u{1}WINDOW_ROLE_NOTIFICATION\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowHint: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WINDOW_HINT_NONE\0\u{1}WINDOW_HINT_SYSTEM_UI\0\u{1}WINDOW_HINT_NOT_RESPONDING\0\u{2}\u{2}WINDOW_HINT_INACCESSIBLE\0\u{2}\u{4}WINDOW_HINT_PROTECTED_CONTENT\0\u{2}\u{8}WINDOW_HINT_AGGRESSIVE_PROTECTED_CONTENT\0\u{2}\u{10}WINDOW_HINT_NOT_VISIBLE_ON_SCREEN\0\u{2}`\u{3}WINDOW_HINT_STATIC_CONTENT\0\u{2}@\u{4}WINDOW_HINT_DYNAMIC_CONTENT\0\u{2}@8WINDOW_HINT_HAS_SHADOW\0\u{2}@@\u{1}WINDOW_HINT_HAS_TRANSPARENCY\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpressionOperator: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MATCH_EXACT\0\u{1}MATCH_CONTAINS\0\u{1}MATCH_ICONTAINS\0\u{1}MATCH_REGEX\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowFilterOperator: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AND\0\u{1}OR\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowListRequestFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WINDOW_LIST_REQUEST_FLAG_NONE\0\u{1}WINDOW_LIST_REQUEST_FLAG_PAGINATED\0\u{1}WINDOW_LIST_REQUEST_FLAG_INCLUDE_HIDDEN_WINDOWS\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowChangeEventType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WINDOW_CHANGE_EVENT_TYPE_NONE\0\u{1}WINDOW_CHANGE_EVENT_TYPE_FOCUSED\0\u{1}WINDOW_CHANGE_EVENT_TYPE_UNFOCUSED\0\u{2}\u{2}WINDOW_CHANGE_EVENT_TYPE_MOVED\0\u{2}\u{4}WINDOW_CHANGE_EVENT_TYPE_RESIZED\0\u{2}\u{8}WINDOW_CHANGE_EVENT_TYPE_CLOSED\0\u{2}\u{10}WINDOW_CHANGE_EVENT_TYPE_METADATA_CHANGED\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowEventSubscriptionFlags: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WINDOW_EVENT_SUBSCRIPTION_FLAG_NONE\0\u{1}WINDOW_EVENT_SUBSCRIPTION_FLAG_SEND_INITIAL_SNAPSHOT\0\u{1}WINDOW_EVENT_SUBSCRIPTION_FLAG_MINIMAL_DATA\0")
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowFilterExpression"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}operator\0\u{1}invert\0\u{1}windowId\0\u{1}pid\0\u{1}windowTitle\0\u{1}applicationName\0\u{1}applicationBundleID\0\u{1}windowClass\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.`operator`) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.invert) }()
      case 3: try {
        var v: UInt64?
        try decoder.decodeSingularFixed64Field(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .windowID(v)
        }
      }()
      case 4: try {
        var v: UInt64?
        try decoder.decodeSingularFixed64Field(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .pid(v)
        }
      }()
      case 5: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .windowTitle(v)
        }
      }()
      case 6: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .applicationName(v)
        }
      }()
      case 7: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .applicationBundleID(v)
        }
      }()
      case 8: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.field != nil {try decoder.handleConflictingOneOf()}
          self.field = .windowClass(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.`operator` != .matchExact {
      try visitor.visitSingularEnumField(value: self.`operator`, fieldNumber: 1)
    }
    if self.invert != false {
      try visitor.visitSingularBoolField(value: self.invert, fieldNumber: 2)
    }
    switch self.field {
    case .windowID?: try {
      guard case .windowID(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularFixed64Field(value: v, fieldNumber: 3)
    }()
    case .pid?: try {
      guard case .pid(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularFixed64Field(value: v, fieldNumber: 4)
    }()
    case .windowTitle?: try {
      guard case .windowTitle(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    }()
    case .applicationName?: try {
      guard case .applicationName(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    }()
    case .applicationBundleID?: try {
      guard case .applicationBundleID(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    }()
    case .windowClass?: try {
      guard case .windowClass(let v)? = self.field else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression) -> Bool {
    if lhs.`operator` != rhs.`operator` {return false}
    if lhs.invert != rhs.invert {return false}
    if lhs.field != rhs.field {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowFilter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowFilter"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}operator\0\u{1}expressions\0\u{1}expression\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.`operator`) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.expressions) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._expression) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.`operator` != .and {
      try visitor.visitSingularEnumField(value: self.`operator`, fieldNumber: 1)
    }
    if !self.expressions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.expressions, fieldNumber: 2)
    }
    try { if let v = self._expression {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilter, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowFilter) -> Bool {
    if lhs.`operator` != rhs.`operator` {return false}
    if lhs.expressions != rhs.expressions {return false}
    if lhs._expression != rhs._expression {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowListRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowListRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}filter\0\u{2}\u{e}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._filter) }()
      case 16: try { try decoder.decodeSingularFixed32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._filter {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularFixed32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowListRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowListRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._filter != rhs._filter {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}windowId\0\u{1}pid\0\u{1}windowTitle\0\u{1}applicationName\0\u{1}applicationBundleID\0\u{1}windowClass\0\u{1}role\0\u{1}bounds\0\u{1}iconHash\0\u{2}\u{3}thumbnail\0\u{1}metadata\0\u{1}hints\0\u{1}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.windowID) }()
      case 2: try { try decoder.decodeSingularFixed64Field(value: &self.pid) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.windowTitle) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.applicationName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.applicationBundleID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.windowClass) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.role) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._bounds) }()
      case 9: try { try decoder.decodeSingularFixed64Field(value: &self._iconHash) }()
      case 12: try { try decoder.decodeSingularBytesField(value: &self._thumbnail) }()
      case 13: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.metadata) }()
      case 14: try { try decoder.decodeSingularFixed32Field(value: &self.hints) }()
      case 15: try { try decoder.decodeSingularFixed32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.windowID != 0 {
      try visitor.visitSingularFixed64Field(value: self.windowID, fieldNumber: 1)
    }
    if self.pid != 0 {
      try visitor.visitSingularFixed64Field(value: self.pid, fieldNumber: 2)
    }
    if !self.windowTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.windowTitle, fieldNumber: 3)
    }
    if !self.applicationName.isEmpty {
      try visitor.visitSingularStringField(value: self.applicationName, fieldNumber: 4)
    }
    if !self.applicationBundleID.isEmpty {
      try visitor.visitSingularStringField(value: self.applicationBundleID, fieldNumber: 5)
    }
    if !self.windowClass.isEmpty {
      try visitor.visitSingularStringField(value: self.windowClass, fieldNumber: 6)
    }
    if self.role != .unknown {
      try visitor.visitSingularEnumField(value: self.role, fieldNumber: 7)
    }
    try { if let v = self._bounds {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._iconHash {
      try visitor.visitSingularFixed64Field(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._thumbnail {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 12)
    } }()
    if !self.metadata.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.metadata, fieldNumber: 13)
    }
    if self.hints != 0 {
      try visitor.visitSingularFixed32Field(value: self.hints, fieldNumber: 14)
    }
    if self.flags != 0 {
      try visitor.visitSingularFixed32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowInfo, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowInfo) -> Bool {
    if lhs.windowID != rhs.windowID {return false}
    if lhs.pid != rhs.pid {return false}
    if lhs.windowTitle != rhs.windowTitle {return false}
    if lhs.applicationName != rhs.applicationName {return false}
    if lhs.applicationBundleID != rhs.applicationBundleID {return false}
    if lhs.windowClass != rhs.windowClass {return false}
    if lhs.role != rhs.role {return false}
    if lhs._bounds != rhs._bounds {return false}
    if lhs._iconHash != rhs._iconHash {return false}
    if lhs._thumbnail != rhs._thumbnail {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.hints != rhs.hints {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowListResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windows\0\u{1}isLastPage\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.windows) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isLastPage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if !self.windows.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.windows, fieldNumber: 2)
    }
    if self.isLastPage != false {
      try visitor.visitSingularBoolField(value: self.isLastPage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowListResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowListResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windows != rhs.windows {return false}
    if lhs.isLastPage != rhs.isLastPage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowInfoRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularFixed64Field(value: &self.windowID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularFixed64Field(value: self.windowID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowInfoResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}info\0")

  fileprivate class _StorageClass {
    var _requestID: UInt64 = 0
    var _info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _requestID = source._requestID
      _info = source._info
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularFixed64Field(value: &_storage._requestID) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._info) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._requestID != 0 {
        try visitor.visitSingularFixed64Field(value: _storage._requestID, fieldNumber: 1)
      }
      try { if let v = _storage._info {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._requestID != rhs_storage._requestID {return false}
        if _storage._info != rhs_storage._info {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowIconRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularFixed64Field(value: &self.windowID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularFixed64Field(value: self.windowID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowIconResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0\u{1}icon\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularFixed64Field(value: &self.windowID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._icon) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularFixed64Field(value: self.windowID, fieldNumber: 2)
    }
    try { if let v = self._icon {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs._icon != rhs._icon {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowThumbnailRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularFixed64Field(value: &self.windowID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularFixed64Field(value: self.windowID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetWindowThumbnailResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}windowId\0\u{1}thumbnail\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularFixed64Field(value: &self.windowID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._thumbnail) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.windowID != 0 {
      try visitor.visitSingularFixed64Field(value: self.windowID, fieldNumber: 2)
    }
    try { if let v = self._thumbnail {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.windowID != rhs.windowID {return false}
    if lhs._thumbnail != rhs._thumbnail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeWindowEventsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}eventMask\0\u{1}filter\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularFixed32Field(value: &self.eventMask) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._filter) }()
      case 16: try { try decoder.decodeSingularFixed32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.eventMask != 0 {
      try visitor.visitSingularFixed32Field(value: self.eventMask, fieldNumber: 2)
    }
    try { if let v = self._filter {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularFixed32Field(value: self.flags, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.eventMask != rhs.eventMask {return false}
    if lhs._filter != rhs._filter {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubscribeWindowEventsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeWindowEventsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnsubscribeWindowEventsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}subscriptionId\0\u{1}isSuccess\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFixed64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._subscriptionID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isSuccess) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularFixed64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._subscriptionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.isSuccess != false {
      try visitor.visitSingularBoolField(value: self.isSuccess, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse, rhs: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._subscriptionID != rhs._subscriptionID {return false}
    if lhs.isSuccess != rhs.isSuccess {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WindowChangedEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}eventType\0\u{1}windowId\0\u{1}info\0")

  fileprivate class _StorageClass {
    var _eventType: UInt32 = 0
    var _windowID: UInt64 = 0
    var _info: Sirius_Msgdef_V1_Channels_Projection_WindowInfo? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _eventType = source._eventType
      _windowID = source._windowID
      _info = source._info
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularFixed32Field(value: &_storage._eventType) }()
        case 2: try { try decoder.decodeSingularFixed64Field(value: &_storage._windowID) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._info) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._eventType != 0 {
        try visitor.visitSingularFixed32Field(value: _storage._eventType, fieldNumber: 1)
      }
      if _storage._windowID != 0 {
        try visitor.visitSingularFixed64Field(value: _storage._windowID, fieldNumber: 2)
      }
      try { if let v = _storage._info {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent, rhs: Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._eventType != rhs_storage._eventType {return false}
        if _storage._windowID != rhs_storage._windowID {return false}
        if _storage._info != rhs_storage._info {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
