// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/fsaccess.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

internal import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// Represents a single mountable file-system entry exposed by a peer.
struct Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Stable identifier for this entry. Issued by the exposing peer and used as the `entryId` argument to `FileSystemMountRequest`.
  var id: Sirius_Msgdef_SRUUID {
    get {return _id ?? Sirius_Msgdef_SRUUID()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {self._id = nil}

  //// Human-readable label for display in the requester's UI (e.g., "내 작업물", "/home/cheesekun", "C:\\").
  //// This field is informational only and MUST NOT be parsed for path semantics.
  var name: String = String()

  //// Free-form metadata for UI hints (icon names, capacity strings, etc.). Format is implementation-defined.
  var metadata: Dictionary<String,String> = [:]

  //// Reserved for future flag bits (e.g., volatile / removable indicators). MUST be zero in the current revision.
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _id: Sirius_Msgdef_SRUUID? = nil
}

//// Detailed error information returned in failed responses across both fsaccess and fsaccess_mount channels.
struct Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// Categorized error code. MUST be set whenever the parent response indicates failure.
  /// @constset: FileSystemErrorCode
  var code: UInt32 = 0

  //// Human-readable diagnostic message. SHOULD be detailed enough to debug from logs alone, including concrete limit values, offending paths, or originating subsystems.
  var message: String = String()

  //// Raw platform error code (POSIX `errno` or Windows `GetLastError`). Optional, provided for debugging only.
  var platformCode: Int32 {
    get {return _platformCode ?? 0}
    set {_platformCode = newValue}
  }
  /// Returns true if `platformCode` has been explicitly set.
  var hasPlatformCode: Bool {return self._platformCode != nil}
  /// Clears the value of `platformCode`. Subsequent reads from it will return its default value.
  mutating func clearPlatformCode() {self._platformCode = nil}

  //// Symbolic name of the platform error (e.g., "EACCES", "ERROR_ACCESS_DENIED"). Optional.
  var platformName: String {
    get {return _platformName ?? String()}
    set {_platformName = newValue}
  }
  /// Returns true if `platformName` has been explicitly set.
  var hasPlatformName: Bool {return self._platformName != nil}
  /// Clears the value of `platformName`. Subsequent reads from it will return its default value.
  mutating func clearPlatformName() {self._platformName = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _platformCode: Int32? = nil
  fileprivate var _platformName: String? = nil
}

//// Requests the list of file-system entries the remote peer is willing to expose.
/// @opcode: 0x8001
struct Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Reserved for future flag bits. MUST be zero in the current revision.
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

//// Response to a FileSystemListRequest.
/// @opcode: 0x8002
struct Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var success: Bool = false

  //// Entries the responding peer is willing to share. MAY be empty even when `success` is true (the peer simply has nothing exposed at the moment).
  var entries: [Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemEntry] = []

  //// Populated when `success` is false.
  var error: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo {
    get {return _error ?? Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  mutating func clearError() {self._error = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _error: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo? = nil
}

//// Requests to mount a file-system entry. The exposing peer prompts the user for consent before responding.
/// @opcode: 0x8003
struct Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Identifier of the entry to mount, taken from `FileSystemListResponse.entries[].id`.
  var entryID: Sirius_Msgdef_SRUUID {
    get {return _entryID ?? Sirius_Msgdef_SRUUID()}
    set {_entryID = newValue}
  }
  /// Returns true if `entryID` has been explicitly set.
  var hasEntryID: Bool {return self._entryID != nil}
  /// Clears the value of `entryID`. Subsequent reads from it will return its default value.
  mutating func clearEntryID() {self._entryID = nil}

  //// Access level requested by the requester. The exposing peer MAY downgrade this in the response (e.g., grant `read` when `readWrite` was requested).
  /// @constset: AccessMode
  var requestedAccess: UInt32 = 0

  //// Optional human-readable reason displayed in the consent dialog (e.g., "AppStream session for Photoshop").
  //// The exposing peer SHOULD treat the value as untrusted display text and MUST NOT use it for any access decision.
  var reason: String {
    get {return _reason ?? String()}
    set {_reason = newValue}
  }
  /// Returns true if `reason` has been explicitly set.
  var hasReason: Bool {return self._reason != nil}
  /// Clears the value of `reason`. Subsequent reads from it will return its default value.
  mutating func clearReason() {self._reason = nil}

  //// Reserved for future flag bits. MUST be zero in the current revision.
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _entryID: Sirius_Msgdef_SRUUID? = nil
  fileprivate var _reason: String? = nil
}

//// Response to a FileSystemMountRequest.
/// @opcode: 0x8004
struct Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var success: Bool = false

  //// Identifier of the granted mount session. Valid only when `success` is true.
  //// The exposing peer opens an `fsaccess_mount` channel keyed by this `sessionId` shortly after sending this response; data-plane operations are conducted on that channel.
  var sessionID: Sirius_Msgdef_SRUUID {
    get {return _sessionID ?? Sirius_Msgdef_SRUUID()}
    set {_sessionID = newValue}
  }
  /// Returns true if `sessionID` has been explicitly set.
  var hasSessionID: Bool {return self._sessionID != nil}
  /// Clears the value of `sessionID`. Subsequent reads from it will return its default value.
  mutating func clearSessionID() {self._sessionID = nil}

  //// Access level actually granted. MUST NOT exceed `requestedAccess`; MAY be lower if the user downgraded the grant (e.g., approved read-only when read-write was requested).
  /// @constset: AccessMode
  var grantedAccess: UInt32 = 0

  //// Populated when `success` is false. Typical codes include `consentDenied`, `notFound`, and `policyViolation`.
  var error: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo {
    get {return _error ?? Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  mutating func clearError() {self._error = nil}

  //// Whether the exposing peer supports byte-range locking on this mount session. When false, all three lock operations on the corresponding `fsaccess_mount` channel (`FileSystemLockRequest`, `FileSystemUnlockRequest`, `FileSystemTestLockRequest`) MUST fail with `notSupported`, and the consuming peer SHOULD avoid sending them. See the `LOCK SEMANTICS` appendix of `fsaccess_mount.mdproto.md` for the full capability-negotiation contract.
  var supportsLocks: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _sessionID: Sirius_Msgdef_SRUUID? = nil
  fileprivate var _error: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo? = nil
}

//// Requests to release an active mount session.
/// @opcode: 0x8005
struct Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  //// Identifier of the session to release.
  var sessionID: Sirius_Msgdef_SRUUID {
    get {return _sessionID ?? Sirius_Msgdef_SRUUID()}
    set {_sessionID = newValue}
  }
  /// Returns true if `sessionID` has been explicitly set.
  var hasSessionID: Bool {return self._sessionID != nil}
  /// Clears the value of `sessionID`. Subsequent reads from it will return its default value.
  mutating func clearSessionID() {self._sessionID = nil}

  //// Reserved for future flag bits. MUST be zero in the current revision.
  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _sessionID: Sirius_Msgdef_SRUUID? = nil
}

//// Response to a FileSystemUnmountRequest.
/// @opcode: 0x8006
struct Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt64 = 0

  var success: Bool = false

  //// Populated when `success` is false. The most common code is `invalidSession` (the session never existed or was already released).
  var error: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo {
    get {return _error ?? Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  mutating func clearError() {self._error = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _error: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.fsaccess"

extension Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileSystemEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{2}\u{c}metadata\0\u{1}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 14: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.metadata) }()
      case 15: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.metadata.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.metadata, fieldNumber: 14)
    }
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemEntry, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemEntry) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ErrorInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}platformCode\0\u{1}platformName\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._platformCode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._platformName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.code != 0 {
      try visitor.visitSingularUInt32Field(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try { if let v = self._platformCode {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._platformName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_ErrorInfo) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs._platformCode != rhs._platformCode {return false}
    if lhs._platformName != rhs._platformName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileSystemListRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{2}\u{e}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 15: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListRequest, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileSystemListResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}success\0\u{1}entries\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 3)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListResponse, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemListResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.success != rhs.success {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileSystemMountRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}entryId\0\u{1}requestedAccess\0\u{1}reason\0\u{2}\u{b}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._entryID) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.requestedAccess) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._reason) }()
      case 15: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._entryID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.requestedAccess != 0 {
      try visitor.visitSingularUInt32Field(value: self.requestedAccess, fieldNumber: 3)
    }
    try { if let v = self._reason {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountRequest, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._entryID != rhs._entryID {return false}
    if lhs.requestedAccess != rhs.requestedAccess {return false}
    if lhs._reason != rhs._reason {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileSystemMountResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}success\0\u{1}sessionId\0\u{1}grantedAccess\0\u{1}error\0\u{1}supportsLocks\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._sessionID) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.grantedAccess) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.supportsLocks) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    try { if let v = self._sessionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.grantedAccess != 0 {
      try visitor.visitSingularUInt32Field(value: self.grantedAccess, fieldNumber: 4)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.supportsLocks != false {
      try visitor.visitSingularBoolField(value: self.supportsLocks, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountResponse, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemMountResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.success != rhs.success {return false}
    if lhs._sessionID != rhs._sessionID {return false}
    if lhs.grantedAccess != rhs.grantedAccess {return false}
    if lhs._error != rhs._error {return false}
    if lhs.supportsLocks != rhs.supportsLocks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileSystemUnmountRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}sessionId\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._sessionID) }()
      case 15: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._sessionID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountRequest, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._sessionID != rhs._sessionID {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileSystemUnmountResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requestId\0\u{1}success\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountResponse, rhs: Sirius_Msgdef_V1_Channels_Fsaccess_FileSystemUnmountResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.success != rhs.success {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
