//
//  projection_data+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius. DO NOT EDIT.
//

import Foundation
import SwiftProtobuf

public extension MessageOpcode {
    static let frameData: MessageOpcode = MessageOpcode(rawValue: 0x8001)
    static let streamDescription: MessageOpcode = MessageOpcode(rawValue: 0x8002)
}

public struct FrameDataHeader: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_FrameDataHeader
    
    public let frameID: UInt64
    public let frameLength: UInt32
    public let presentationTimestamp: UInt64
    public let isKeyFrame: Bool

    public init(frameID: UInt64, frameLength: UInt32, presentationTimestamp: UInt64, isKeyFrame: Bool) {
        self.frameID = frameID
        self.frameLength = frameLength
        self.presentationTimestamp = presentationTimestamp
        self.isKeyFrame = isKeyFrame
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_FrameDataHeader) throws {
        self.frameID = protobufMessage.frameID
        self.frameLength = protobufMessage.frameLength
        self.presentationTimestamp = protobufMessage.presentationTimestamp
        self.isKeyFrame = protobufMessage.isKeyFrame
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.frameID = self.frameID
        message.frameLength = self.frameLength
        message.presentationTimestamp = self.presentationTimestamp
        message.isKeyFrame = self.isKeyFrame

        return message
    }
}

public extension FrameDataHeader {
    func serialize() -> Data {
        let protobufMessage = self.toProtobufMessage()
        return try! protobufMessage.serializedData()
    }
}
