//
//  winman_query+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius. DO NOT EDIT.
//

import Foundation
import SwiftProtobuf

public extension MessageOpcode {
    static let windowListRequest: MessageOpcode = MessageOpcode(rawValue: 0x8101)
    static let windowListResponse: MessageOpcode = MessageOpcode(rawValue: 0x8042)
}

public struct WindowListRequestFlagSet: OptionSet, Hashable, Equatable {
    public let rawValue: UInt32
    
    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }
    
    public static let none = Self([])
    public static let paginated = Self(rawValue: 1 << 0)
    public static let includeHiddenWindows = Self(rawValue: 1 << 1)
}

public struct WindowEventSubscriptionFlagSet: OptionSet, Hashable, Equatable {
    public let rawValue: UInt32
    
    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }
    
    public static let none = Self([])
    public static let sendInitialSnapshot = Self(rawValue: 1 << 0)
    public static let minimalData = Self(rawValue: 1 << 1)
}

public struct WindowChangeEventType: OptionSet, Hashable, Equatable {
    public let rawValue: UInt32
    
    public init(rawValue: UInt32) {
        self.rawValue = rawValue
    }
    
    public static let none = Self([])
    public static let focused = Self(rawValue: 1 << 0)
    public static let unfocused = Self(rawValue: 1 << 1)
    public static let moved = Self(rawValue: 1 << 2)
    public static let resized = Self(rawValue: 1 << 3)
    public static let closed = Self(rawValue: 1 << 4)
    public static let metadataChanged = Self(rawValue: 1 << 5)
}

public struct WindowListRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_WindowListRequest
    
    public let requestID: UInt64
    public let filter: WindowFilter?
    public let flags: WindowListRequestFlagSet


    public init(requestID: UInt64, filter: WindowFilter?, flags: WindowListRequestFlagSet) {
        self.requestID = requestID
        self.filter = filter
        self.flags = flags
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_WindowListRequest) throws {
        self.requestID = protobufMessage.requestID
        if protobufMessage.hasFilter {
            let parsedFilter = try WindowFilter(from: protobufMessage.filter)
            self.filter = parsedFilter.isEmpty ? nil : parsedFilter
        } else {
            self.filter = nil
        }
        self.flags = WindowListRequestFlagSet(rawValue: protobufMessage.flags)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        if let filter = self.filter, !filter.isEmpty {
            message.filter = filter.toProtobufMessage()
        }
        message.flags = self.flags.rawValue

        return message
    }
}

public struct WindowInfo: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_WindowInfo
    
    public let windowID: UInt64
    public let pid: UInt64
    public let windowTitle: String
    public let applicationName: String
    public let applicationBundleID: String
    public let windowClass: String
    public let role: WindowRole
    public let bounds: SRRect
    public let iconHash: UInt64?
    public let thumbnail: Data?
    public let metadata: [String: String]
    public let hints: WindowHints
    public let flags: WindowInfoFlags


    public init(
        windowID: UInt64,
        pid: UInt64,
        windowTitle: String,
        applicationName: String,
        applicationBundleID: String,
        windowClass: String,
        role: WindowRole,
        bounds: SRRect,
        iconHash: UInt64?,
        thumbnail: Data?,
        metadata: [String: String],
        hints: WindowHints,
        flags: WindowInfoFlags
    ) {
        self.windowID = windowID
        self.pid = pid
        self.windowTitle = windowTitle
        self.applicationName = applicationName
        self.applicationBundleID = applicationBundleID
        self.windowClass = windowClass
        self.role = role
        self.bounds = bounds
        self.iconHash = iconHash
        self.thumbnail = thumbnail
        self.metadata = metadata
        self.hints = hints
        self.flags = flags
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_WindowInfo) throws {
        self.windowID = protobufMessage.windowID
        self.pid = protobufMessage.pid
        self.windowTitle = protobufMessage.windowTitle
        self.applicationName = protobufMessage.applicationName
        self.applicationBundleID = protobufMessage.applicationBundleID
        self.windowClass = protobufMessage.windowClass
        self.role = WindowRole(from: protobufMessage.role)
        self.bounds = SRRect(from: protobufMessage.bounds)
        self.iconHash = protobufMessage.hasIconHash ? protobufMessage.iconHash : nil
        self.thumbnail = protobufMessage.hasThumbnail ? protobufMessage.thumbnail : nil
        self.metadata = protobufMessage.metadata
        self.hints = WindowHints(rawValue: protobufMessage.hints)
        self.flags = WindowInfoFlags(rawValue: protobufMessage.flags)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.windowID = self.windowID
        message.pid = self.pid
        message.windowTitle = self.windowTitle
        message.applicationName = self.applicationName
        message.applicationBundleID = self.applicationBundleID
        message.windowClass = self.windowClass
        message.role = self.role.toProtobufEnum()
        message.bounds = self.bounds.toProtobufMessage()
        if let iconHash = self.iconHash {
            message.iconHash = iconHash
        }
        if let thumbnail = self.thumbnail {
            message.thumbnail = thumbnail
        }
        message.metadata = self.metadata
        message.hints = self.hints.rawValue
        message.flags = self.flags.rawValue

        return message
    }
}

public struct WindowListResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_WindowListResponse
    
    public let requestID: UInt64
    public let windows: [WindowInfo]
    public let isLastPage: Bool


    public init(requestID: UInt64, windows: [WindowInfo], isLastPage: Bool) {
        self.requestID = requestID
        self.windows = windows
        self.isLastPage = isLastPage
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_WindowListResponse) throws {
        self.requestID = protobufMessage.requestID
        self.windows = try protobufMessage.windows.map { try WindowInfo(from: $0) }
        self.isLastPage = protobufMessage.isLastPage
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.windows = self.windows.map { $0.toProtobufMessage() }
        message.isLastPage = self.isLastPage

        return message
    }
}

public struct GetWindowInfoRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest
    
    public let requestID: UInt64
    public let windowID: UInt64


    public init(requestID: UInt64, windowID: UInt64) {
        self.requestID = requestID
        self.windowID = windowID
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoRequest) throws {
        self.requestID = protobufMessage.requestID
        self.windowID = protobufMessage.windowID
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.windowID = self.windowID

        return message
    }
}

public struct GetWindowInfoResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse
    
    public let requestID: UInt64
    public let info: WindowInfo?


    public init(requestID: UInt64, info: WindowInfo?) {
        self.requestID = requestID
        self.info = info
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_GetWindowInfoResponse) throws {
        self.requestID = protobufMessage.requestID
        self.info = protobufMessage.hasInfo ? try WindowInfo(from: protobufMessage.info) : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        if let info = self.info {
            message.info = info.toProtobufMessage()
        }

        return message
    }
}

public struct GetWindowIconRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest
    
    public let requestID: UInt64
    public let windowID: UInt64


    public init(requestID: UInt64, windowID: UInt64) {
        self.requestID = requestID
        self.windowID = windowID
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconRequest) throws {
        self.requestID = protobufMessage.requestID
        self.windowID = protobufMessage.windowID
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.windowID = self.windowID

        return message
    }
}

public struct GetWindowIconResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse
    
    public let requestID: UInt64
    public let windowID: UInt64
    public let icon: Data?


    public init(requestID: UInt64, windowID: UInt64, icon: Data?) {
        self.requestID = requestID
        self.windowID = windowID
        self.icon = icon
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_GetWindowIconResponse) throws {
        self.requestID = protobufMessage.requestID
        self.windowID = protobufMessage.windowID
        self.icon = protobufMessage.hasIcon ? protobufMessage.icon : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.windowID = self.windowID
        if let icon = self.icon {
            message.icon = icon
        }

        return message
    }
}

public struct GetWindowThumbnailRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest
    
    public let requestID: UInt64
    public let windowID: UInt64


    public init(requestID: UInt64, windowID: UInt64) {
        self.requestID = requestID
        self.windowID = windowID
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailRequest) throws {
        self.requestID = protobufMessage.requestID
        self.windowID = protobufMessage.windowID
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.windowID = self.windowID

        return message
    }
}

public struct GetWindowThumbnailResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse
    
    public let requestID: UInt64
    public let windowID: UInt64
    public let thumbnail: Data?


    public init(requestID: UInt64, windowID: UInt64, thumbnail: Data?) {
        self.requestID = requestID
        self.windowID = windowID
        self.thumbnail = thumbnail
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_GetWindowThumbnailResponse) throws {
        self.requestID = protobufMessage.requestID
        self.windowID = protobufMessage.windowID
        self.thumbnail = protobufMessage.hasThumbnail ? protobufMessage.thumbnail : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.windowID = self.windowID
        if let thumbnail = self.thumbnail {
            message.thumbnail = thumbnail
        }

        return message
    }
}

public struct SubscribeWindowEventsRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest
    
    public let requestID: UInt64
    public let eventMask: WindowChangeEventType
    public let filter: WindowFilter?
    public let flags: WindowEventSubscriptionFlagSet


    public init(requestID: UInt64, eventMask: WindowChangeEventType, filter: WindowFilter?, flags: WindowEventSubscriptionFlagSet) {
        self.requestID = requestID
        self.eventMask = eventMask
        self.filter = filter
        self.flags = flags
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsRequest) throws {
        self.requestID = protobufMessage.requestID
        self.eventMask = WindowChangeEventType(rawValue: protobufMessage.eventMask)
        if protobufMessage.hasFilter {
            let parsedFilter = try WindowFilter(from: protobufMessage.filter)
            self.filter = parsedFilter.isEmpty ? nil : parsedFilter
        } else {
            self.filter = nil
        }
        self.flags = WindowEventSubscriptionFlagSet(rawValue: protobufMessage.flags)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.eventMask = self.eventMask.rawValue
        if let filter = self.filter, !filter.isEmpty {
            message.filter = filter.toProtobufMessage()
        }
        message.flags = self.flags.rawValue

        return message
    }
}

public struct SubscribeWindowEventsResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse
    
    public let requestID: UInt64
    public let subscriptionID: UUID


    public init(requestID: UInt64, subscriptionID: UUID) {
        self.requestID = requestID
        self.subscriptionID = subscriptionID
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_SubscribeWindowEventsResponse) throws {
        self.requestID = protobufMessage.requestID
        self.subscriptionID = UUID(msgdef: protobufMessage.subscriptionID)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.subscriptionID = self.subscriptionID.asMsgDef()

        return message
    }
}

public struct UnsubscribeWindowEventsRequest: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest
    
    public let requestID: UInt64
    public let subscriptionID: UUID


    public init(requestID: UInt64, subscriptionID: UUID) {
        self.requestID = requestID
        self.subscriptionID = subscriptionID
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsRequest) throws {
        self.requestID = protobufMessage.requestID
        self.subscriptionID = UUID(msgdef: protobufMessage.subscriptionID)
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.subscriptionID = self.subscriptionID.asMsgDef()

        return message
    }
}

public struct UnsubscribeWindowEventsResponse: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse
    
    public let requestID: UInt64
    public let subscriptionID: UUID
    public let isSuccess: Bool


    public init(requestID: UInt64, subscriptionID: UUID, isSuccess: Bool) {
        self.requestID = requestID
        self.subscriptionID = subscriptionID
        self.isSuccess = isSuccess
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_UnsubscribeWindowEventsResponse) throws {
        self.requestID = protobufMessage.requestID
        self.subscriptionID = UUID(msgdef: protobufMessage.subscriptionID)
        self.isSuccess = protobufMessage.isSuccess
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.requestID = self.requestID
        message.subscriptionID = self.subscriptionID.asMsgDef()
        message.isSuccess = self.isSuccess

        return message
    }
}

public struct WindowChangedEvent: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent
    
    public let eventType: WindowChangeEventType
    public let windowID: UInt64
    public let info: WindowInfo?


    public init(eventType: WindowChangeEventType, windowID: UInt64, info: WindowInfo?) {
        self.eventType = eventType
        self.windowID = windowID
        self.info = info
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_WindowChangedEvent) throws {
        self.eventType = WindowChangeEventType(rawValue: protobufMessage.eventType)
        self.windowID = protobufMessage.windowID
        self.info = protobufMessage.hasInfo ? try WindowInfo(from: protobufMessage.info) : nil
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.eventType = self.eventType.rawValue
        message.windowID = self.windowID
        if let info = self.info {
            message.info = info.toProtobufMessage()
        }

        return message
    }
}

private extension WindowFilterExpressionOperator {
    func toProtobufEnum() -> Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpressionOperator {
        switch self {
        case .exact:
            return .matchExact
        case .contains:
            return .matchContains
        case .icontains:
            return .matchIcontains
        case .regex:
            return .matchRegex
        }
    }
    
    static func fromProtobufEnum(
        _ protobufEnum: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpressionOperator
    ) -> Self {
        switch protobufEnum {
        case .matchExact:
            return .exact
        case .matchContains:
            return .contains
        case .matchIcontains:
            return .icontains
        case .matchRegex:
            return .regex
        case .UNRECOGNIZED:
            return .exact
        }
    }
}

private extension WindowFilter.Operator {
    func toProtobufEnum() -> Sirius_Msgdef_V1_Channels_Projection_WindowFilterOperator {
        switch self {
        case .and:
            return .and
        case .or:
            return .or
        }
    }
    
    static func fromProtobufEnum(
        _ protobufEnum: Sirius_Msgdef_V1_Channels_Projection_WindowFilterOperator
    ) -> Self {
        switch protobufEnum {
        case .and:
            return .and
        case .or:
            return .or
        case .UNRECOGNIZED:
            return .and
        }
    }
}

private extension WindowRole {
    init(from protobufEnum: Sirius_Msgdef_V1_Channels_Projection_WindowRole) {
        self.init(rawValue: UInt32(protobufEnum.rawValue))
    }
    
    func toProtobufEnum() -> Sirius_Msgdef_V1_Channels_Projection_WindowRole {
        return Sirius_Msgdef_V1_Channels_Projection_WindowRole(rawValue: Int(self.rawValue)) ?? .unknown
    }
}

private extension WindowFilterExpression {
    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression) throws {
        let field: WindowFilterExpressionField
        switch protobufMessage.field {
        case .windowID(let val):
            field = .windowID(val)
        case .pid(let val):
            field = .pid(val)
        case .windowTitle(let val):
            field = .windowTitle(val)
        case .applicationName(let val):
            field = .applicationName(val)
        case .applicationBundleID(let val):
            field = .applicationBundleID(val)
        case .windowClass(let val):
            field = .windowClass(val)
        case .none:
            throw SiriusMessageError.invalidProtobufMessage
        }
        
        self.init(field)
        self.operator = WindowFilterExpressionOperator.fromProtobufEnum(protobufMessage.operator)
        self.invert = protobufMessage.invert
    }
    
    func toProtobufMessage() -> Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression {
        var message = Sirius_Msgdef_V1_Channels_Projection_WindowFilterExpression()
        
        message.operator = self.operator.toProtobufEnum()
        message.invert = self.invert
        switch self.field {
        case .windowID(let val):
            message.field = .windowID(val)
        case .pid(let val):
            message.field = .pid(val)
        case .windowTitle(let val):
            message.field = .windowTitle(val)
        case .applicationName(let val):
            message.field = .applicationName(val)
        case .applicationBundleID(let val):
            message.field = .applicationBundleID(val)
        case .windowClass(let val):
            message.field = .windowClass(val)
        }
        
        return message
    }
}

private extension WindowFilter {
    var isEmpty: Bool {
        expression == nil && expressions.isEmpty
    }
    
    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Projection_WindowFilter) throws {
        let op = WindowFilter.Operator.fromProtobufEnum(protobufMessage.operator)
        if !protobufMessage.expressions.isEmpty {
            self.init(op, expressions: try protobufMessage.expressions.map { try WindowFilter(from: $0) })
        } else if protobufMessage.hasExpression {
            self.init(expression: try WindowFilterExpression(from: protobufMessage.expression))
        } else {
            self.init(op, expressions: [])
        }
    }
    
    func toProtobufMessage() -> Sirius_Msgdef_V1_Channels_Projection_WindowFilter {
        var message = Sirius_Msgdef_V1_Channels_Projection_WindowFilter()
        
        message.operator = self.operator.toProtobufEnum()
        if let expression = self.expression {
            message.expression = expression.toProtobufMessage()
        } else {
            message.expressions = self.expressions.map { $0.toProtobufMessage() }
        }
        
        return message
    }
}
