// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: msgdef/v1/channels/hidio/hid_keyboard.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

internal import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// Keyboard Layout 정의
struct Sirius_Msgdef_V1_Channels_Hidio_KeyboardLayout: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// @constset: KeyboardLayoutId
  var layoutID: UInt32 = 0

  /// Locale ID
  /// - MS-LCID를 따릅니다.
  /// - (eg. 0x0409 - en-US, 0x0412 - ko-KR)
  /// - see https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f
  var localeID: UInt32 = 0

  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sirius_Msgdef_V1_Channels_Hidio_KeyboardHack: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var identifier: String = String()

  var args: Dictionary<String,String> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sirius_Msgdef_V1_Channels_Hidio_KeyboardSetupEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var preferredLayouts: [Sirius_Msgdef_V1_Channels_Hidio_KeyboardLayout] = []

  var hacks: [Sirius_Msgdef_V1_Channels_Hidio_KeyboardHack] = []

  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Sirius_Msgdef_V1_Channels_Hidio_KeyboardEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// @constset: KeyboardEventType
  var eventType: UInt32 = 0

  var scanCode: UInt32 = 0

  var keyCode: UInt32 = 0

  /// @optionset: KeyboardModifier
  var modifiers: UInt32 = 0

  var flags: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sirius.msgdef.v1.channels.hidio"

extension Sirius_Msgdef_V1_Channels_Hidio_KeyboardLayout: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KeyboardLayout"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}layoutId\0\u{1}localeId\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.layoutID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.localeID) }()
      case 15: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.layoutID != 0 {
      try visitor.visitSingularUInt32Field(value: self.layoutID, fieldNumber: 1)
    }
    if self.localeID != 0 {
      try visitor.visitSingularUInt32Field(value: self.localeID, fieldNumber: 2)
    }
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardLayout, rhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardLayout) -> Bool {
    if lhs.layoutID != rhs.layoutID {return false}
    if lhs.localeID != rhs.localeID {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Hidio_KeyboardHack: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KeyboardHack"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}identifier\0\u{1}args\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.identifier) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.args) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.identifier.isEmpty {
      try visitor.visitSingularStringField(value: self.identifier, fieldNumber: 1)
    }
    if !self.args.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.args, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardHack, rhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardHack) -> Bool {
    if lhs.identifier != rhs.identifier {return false}
    if lhs.args != rhs.args {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Hidio_KeyboardSetupEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KeyboardSetupEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}preferredLayouts\0\u{1}hacks\0\u{2}\u{d}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.preferredLayouts) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.hacks) }()
      case 15: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.preferredLayouts.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.preferredLayouts, fieldNumber: 1)
    }
    if !self.hacks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.hacks, fieldNumber: 2)
    }
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardSetupEvent, rhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardSetupEvent) -> Bool {
    if lhs.preferredLayouts != rhs.preferredLayouts {return false}
    if lhs.hacks != rhs.hacks {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sirius_Msgdef_V1_Channels_Hidio_KeyboardEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KeyboardEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}eventType\0\u{1}scanCode\0\u{1}keyCode\0\u{1}modifiers\0\u{1}flags\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.eventType) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.scanCode) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.keyCode) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.modifiers) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.flags) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.eventType != 0 {
      try visitor.visitSingularUInt32Field(value: self.eventType, fieldNumber: 1)
    }
    if self.scanCode != 0 {
      try visitor.visitSingularUInt32Field(value: self.scanCode, fieldNumber: 2)
    }
    if self.keyCode != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyCode, fieldNumber: 3)
    }
    if self.modifiers != 0 {
      try visitor.visitSingularUInt32Field(value: self.modifiers, fieldNumber: 4)
    }
    if self.flags != 0 {
      try visitor.visitSingularUInt32Field(value: self.flags, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardEvent, rhs: Sirius_Msgdef_V1_Channels_Hidio_KeyboardEvent) -> Bool {
    if lhs.eventType != rhs.eventType {return false}
    if lhs.scanCode != rhs.scanCode {return false}
    if lhs.keyCode != rhs.keyCode {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
