//
//  hidio+Sirius.swift
//  SiriusKit
//
//  Auto-generated by protoc-gen-sirius. DO NOT EDIT.
//

import Foundation
import SwiftProtobuf

extension MessageOpcode {
    public static let hidioPacket: MessageOpcode = MessageOpcode(rawValue: 0x8001)
}

public struct HIDIOPacket: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Hidio_HIDIOPacket
    
    public let sequenceNumber: UInt64
    public let timestamp: UInt64
    public let events: [HIDEvent]


    init(sequenceNumber: UInt64, timestamp: UInt64, events: [HIDEvent]) {
        self.sequenceNumber = sequenceNumber
        self.timestamp = timestamp
        self.events = events
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Hidio_HIDIOPacket) throws {
        self.sequenceNumber = protobufMessage.sequenceNumber
        self.timestamp = protobufMessage.timestamp
        self.events = try protobufMessage.events.map { try HIDEvent(from: $0) }
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        message.sequenceNumber = self.sequenceNumber
        message.timestamp = self.timestamp
        message.events = self.events.map { $0.toProtobufMessage() }

        return message
    }
}

public struct HIDEvent: SiriusMessage {
    typealias ProtobufMessage = Sirius_Msgdef_V1_Channels_Hidio_HIDEvent
    
    public enum OneOf_Event {
        case rawEvent(RawEvent)
        case keyboardSetupEvent(KeyboardSetupEvent)
        case keyboardEvent(KeyboardEvent)
        case mouseMoveEvent(MouseMoveEvent)
        case mouseButtonEvent(MouseButtonEvent)
        case mouseWheelEvent(MouseWheelEvent)
        case none
    }


    public let event: OneOf_Event

    init(event: OneOf_Event) {
        self.event = event
    }

    init(from protobufMessage: Sirius_Msgdef_V1_Channels_Hidio_HIDEvent) throws {
        switch protobufMessage.event {
        case .rawEvent(let val):
            self.event = .rawEvent(try RawEvent(from: val))
            break
        case .keyboardSetupEvent(let val):
            self.event = .keyboardSetupEvent(try KeyboardSetupEvent(from: val))
            break
        case .keyboardEvent(let val):
            self.event = .keyboardEvent(try KeyboardEvent(from: val))
            break
        case .mouseMoveEvent(let val):
            self.event = .mouseMoveEvent(try MouseMoveEvent(from: val))
            break
        case .mouseButtonEvent(let val):
            self.event = .mouseButtonEvent(try MouseButtonEvent(from: val))
            break
        case .mouseWheelEvent(let val):
            self.event = .mouseWheelEvent(try MouseWheelEvent(from: val))
            break
        case .none:
            self.event = .none
            break
        }
    }

    func toProtobufMessage() -> ProtobufMessage {
        var message = ProtobufMessage()

        switch self.event {
        case .rawEvent(let val):
            message.event = .rawEvent(val.toProtobufMessage())
            break
        case .keyboardSetupEvent(let val):
            message.event = .keyboardSetupEvent(val.toProtobufMessage())
            break
        case .keyboardEvent(let val):
            message.event = .keyboardEvent(val.toProtobufMessage())
            break
        case .mouseMoveEvent(let val):
            message.event = .mouseMoveEvent(val.toProtobufMessage())
            break
        case .mouseButtonEvent(let val):
            message.event = .mouseButtonEvent(val.toProtobufMessage())
            break
        case .mouseWheelEvent(let val):
            message.event = .mouseWheelEvent(val.toProtobufMessage())
            break
        case .none:
            break
        }

        return message
    }
}

