//
//  Keycode+Description.swift
//  SiriusKit
//
//  Created by Gyuhwan Park on 12/18/25.
//

import Foundation

extension LinuxKeycode: CustomStringConvertible {
    public var description: String {
        return Self.descriptions[self] ?? "Raw Keycode (\(self.rawValue))"
    }

    fileprivate static let descriptions: [LinuxKeycode: String] = [
        .KEY_RESERVED: "Reserved",
        .KEY_ESC: "Esc",
        .KEY_1: "1",
        .KEY_2: "2",
        .KEY_3: "3",
        .KEY_4: "4",
        .KEY_5: "5",
        .KEY_6: "6",
        .KEY_7: "7",
        .KEY_8: "8",
        .KEY_9: "9",
        .KEY_0: "0",
        .KEY_MINUS: "-",
        .KEY_EQUAL: "=",
        .KEY_BACKSPACE: "Backspace",
        .KEY_TAB: "Tab",
        .KEY_Q: "Q",
        .KEY_W: "W",
        .KEY_E: "E",
        .KEY_R: "R",
        .KEY_T: "T",
        .KEY_Y: "Y",
        .KEY_U: "U",
        .KEY_I: "I",
        .KEY_O: "O",
        .KEY_P: "P",
        .KEY_LEFTBRACE: "[",
        .KEY_RIGHTBRACE: "]",
        .KEY_ENTER: "Enter",
        .KEY_LEFTCTRL: "Left Ctrl",
        .KEY_A: "A",
        .KEY_S: "S",
        .KEY_D: "D",
        .KEY_F: "F",
        .KEY_G: "G",
        .KEY_H: "H",
        .KEY_J: "J",
        .KEY_K: "K",
        .KEY_L: "L",
        .KEY_SEMICOLON: ";",
        .KEY_APOSTROPHE: "'",
        .KEY_GRAVE: "`",
        .KEY_LEFTSHIFT: "Left Shift",
        .KEY_BACKSLASH: "\\",
        .KEY_Z: "Z",
        .KEY_X: "X",
        .KEY_C: "C",
        .KEY_V: "V",
        .KEY_B: "B",
        .KEY_N: "N",
        .KEY_M: "M",
        .KEY_COMMA: ",",
        .KEY_DOT: ".",
        .KEY_SLASH: "/",
        .KEY_RIGHTSHIFT: "Right Shift",
        .KEY_KPASTERISK: "Keypad *",
        .KEY_LEFTALT: "Left Alt",
        .KEY_SPACE: "Space",
        .KEY_CAPSLOCK: "Caps Lock",
        .KEY_F1: "F1",
        .KEY_F2: "F2",
        .KEY_F3: "F3",
        .KEY_F4: "F4",
        .KEY_F5: "F5",
        .KEY_F6: "F6",
        .KEY_F7: "F7",
        .KEY_F8: "F8",
        .KEY_F9: "F9",
        .KEY_F10: "F10",
        .KEY_NUMLOCK: "Num Lock",
        .KEY_SCROLLLOCK: "Scroll Lock",
        .KEY_KP7: "Keypad 7",
        .KEY_KP8: "Keypad 8",
        .KEY_KP9: "Keypad 9",
        .KEY_KPMINUS: "Keypad -",
        .KEY_KP4: "Keypad 4",
        .KEY_KP5: "Keypad 5",
        .KEY_KP6: "Keypad 6",
        .KEY_KPPLUS: "Keypad +",
        .KEY_KP1: "Keypad 1",
        .KEY_KP2: "Keypad 2",
        .KEY_KP3: "Keypad 3",
        .KEY_KP0: "Keypad 0",
        .KEY_KPDOT: "Keypad .",
        .KEY_ZENKAKUHANKAKU: "Zenkaku/Hankaku",
        .KEY_102ND: "102nd",
        .KEY_F11: "F11",
        .KEY_F12: "F12",
        .KEY_RO: "RO",
        .KEY_KATAKANA: "Katakana",
        .KEY_HIRAGANA: "Hiragana",
        .KEY_HENKAN: "Henkan",
        .KEY_KATAKANAHIRAGANA: "Katakana/Hiragana",
        .KEY_MUHENKAN: "Muhenkan",
        .KEY_KPJPCOMMA: "Keypad , (JIS)",
        .KEY_KPENTER: "Keypad Enter",
        .KEY_RIGHTCTRL: "Right Ctrl",
        .KEY_KPSLASH: "Keypad /",
        .KEY_SYSRQ: "SysRq",
        .KEY_RIGHTALT: "Right Alt",
        .KEY_LINEFEED: "Line Feed",
        .KEY_HOME: "Home",
        .KEY_UP: "Up",
        .KEY_PAGEUP: "Page Up",
        .KEY_LEFT: "Left",
        .KEY_RIGHT: "Right",
        .KEY_END: "End",
        .KEY_DOWN: "Down",
        .KEY_PAGEDOWN: "Page Down",
        .KEY_INSERT: "Insert",
        .KEY_DELETE: "Delete",
        .KEY_MACRO: "Macro",
        .KEY_MUTE: "Mute",
        .KEY_VOLUMEDOWN: "Volume Down",
        .KEY_VOLUMEUP: "Volume Up",
        .KEY_POWER: "Power",
        .KEY_KPEQUAL: "Keypad =",
        .KEY_KPPLUSMINUS: "Keypad +/-",
        .KEY_PAUSE: "Pause",
        .KEY_SCALE: "Scale",
        .KEY_KPCOMMA: "Keypad ,",
        .KEY_HANGEUL: "Hangeul",
        .KEY_HANJA: "Hanja",
        .KEY_YEN: "Yen",
        .KEY_LEFTMETA: "Left Meta",
        .KEY_RIGHTMETA: "Right Meta",
        .KEY_COMPOSE: "Compose",
        .KEY_STOP: "Stop",
        .KEY_AGAIN: "Again",
        .KEY_PROPS: "Props",
        .KEY_UNDO: "Undo",
        .KEY_FRONT: "Front",
        .KEY_COPY: "Copy",
        .KEY_OPEN: "Open",
        .KEY_PASTE: "Paste",
        .KEY_FIND: "Find",
        .KEY_CUT: "Cut",
        .KEY_HELP: "Help",
        .KEY_MENU: "Menu",
        .KEY_CALC: "Calc",
        .KEY_SETUP: "Setup",
        .KEY_SLEEP: "Sleep",
        .KEY_WAKEUP: "Wakeup",
        .KEY_FILE: "File",
        .KEY_SENDFILE: "Send File",
        .KEY_DELETEFILE: "Delete File",
        .KEY_XFER: "X-fer",
        .KEY_PROG1: "Prog1",
        .KEY_PROG2: "Prog2",
        .KEY_WWW: "WWW",
        .KEY_MSDOS: "MSDOS",
        .KEY_COFFEE: "Screen Lock", // or Coffee
        .KEY_ROTATE_DISPLAY: "Rotate Display",
        .KEY_CYCLEWINDOWS: "Cycle Windows",
        .KEY_MAIL: "Mail",
        .KEY_BOOKMARKS: "Bookmarks",
        .KEY_COMPUTER: "Computer",
        .KEY_BACK: "Back",
        .KEY_FORWARD: "Forward",
        .KEY_CLOSECD: "Close CD",
        .KEY_EJECTCD: "Eject CD",
        .KEY_EJECTCLOSECD: "Eject/Close CD",
        .KEY_NEXTSONG: "Next Song",
        .KEY_PLAYPAUSE: "Play/Pause",
        .KEY_PREVIOUSSONG: "Previous Song",
        .KEY_STOPCD: "Stop CD",
        .KEY_RECORD: "Record",
        .KEY_REWIND: "Rewind",
        .KEY_PHONE: "Phone",
        .KEY_ISO: "ISO",
        .KEY_CONFIG: "Config",
        .KEY_HOMEPAGE: "Homepage",
        .KEY_REFRESH: "Refresh",
        .KEY_EXIT: "Exit",
        .KEY_MOVE: "Move",
        .KEY_EDIT: "Edit",
        .KEY_SCROLLUP: "Scroll Up",
        .KEY_SCROLLDOWN: "Scroll Down",
        .KEY_KPLEFTPAREN: "Keypad (",
        .KEY_KPRIGHTPAREN: "Keypad )",
        .KEY_NEW: "New",
        .KEY_REDO: "Redo",
        .KEY_F13: "F13",
        .KEY_F14: "F14",
        .KEY_F15: "F15",
        .KEY_F16: "F16",
        .KEY_F17: "F17",
        .KEY_F18: "F18",
        .KEY_F19: "F19",
        .KEY_F20: "F20",
        .KEY_F21: "F21",
        .KEY_F22: "F22",
        .KEY_F23: "F23",
        .KEY_F24: "F24",
        .KEY_PLAYCD: "Play CD",
        .KEY_PAUSECD: "Pause CD",
        .KEY_PROG3: "Prog3",
        .KEY_PROG4: "Prog4",
        .KEY_ALL_APPLICATIONS: "All Applications",
        .KEY_SUSPEND: "Suspend",
        .KEY_CLOSE: "Close",
        .KEY_PLAY: "Play",
        .KEY_FASTFORWARD: "Fast Forward",
        .KEY_BASSBOOST: "Bass Boost",
        .KEY_PRINT: "Print",
        .KEY_HP: "HP",
        .KEY_CAMERA: "Camera",
        .KEY_SOUND: "Sound",
        .KEY_QUESTION: "Question",
        .KEY_EMAIL: "Email",
        .KEY_CHAT: "Chat",
        .KEY_SEARCH: "Search",
        .KEY_CONNECT: "Connect",
        .KEY_FINANCE: "Finance",
        .KEY_SPORT: "Sport",
        .KEY_SHOP: "Shop",
        .KEY_ALTERASE: "Alt Erase",
        .KEY_CANCEL: "Cancel",
        .KEY_BRIGHTNESSDOWN: "Brightness Down",
        .KEY_BRIGHTNESSUP: "Brightness Up",
        .KEY_MEDIA: "Media",
        .KEY_SWITCHVIDEOMODE: "Switch Video Mode",
        .KEY_KBDILLUMTOGGLE: "Kbd Illum Toggle",
        .KEY_KBDILLUMDOWN: "Kbd Illum Down",
        .KEY_KBDILLUMUP: "Kbd Illum Up",
        .KEY_SEND: "Send",
        .KEY_REPLY: "Reply",
        .KEY_FORWARDMAIL: "Forward Mail",
        .KEY_SAVE: "Save",
        .KEY_DOCUMENTS: "Documents",
        .KEY_BATTERY: "Battery",
        .KEY_BLUETOOTH: "Bluetooth",
        .KEY_WLAN: "WLAN",
        .KEY_UWB: "UWB",
        .KEY_UNKNOWN: "Unknown",
        .KEY_VIDEO_NEXT: "Video Next",
        .KEY_VIDEO_PREV: "Video Prev",
        .KEY_BRIGHTNESS_CYCLE: "Brightness Cycle",
        .KEY_BRIGHTNESS_AUTO: "Brightness Auto",
        .KEY_DISPLAY_OFF: "Display Off",
        .KEY_WWAN: "WWAN",
        .KEY_RFKILL: "RF Kill",
        .KEY_MICMUTE: "Mic Mute"
    ]
}
